package io.metaloom.cortex.node.watermark;

import static io.metaloom.cortex.media.test.assertj.NodeAssertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import io.metaloom.cortex.api.node.NodeResult;
import io.metaloom.cortex.api.node.context.NodeContext;
import io.metaloom.cortex.api.option.CortexOptions;
import io.metaloom.cortex.node.watermark.FfmpegRunner.VideoDimensions;
import io.metaloom.cortex.pipeline.test.StubLoomMedia;
import io.metaloom.utils.hash.SHA512;

/**
 * Unit test for {@link WatermarkNode}'s video path and {@link FfmpegRunner}.
 *
 * <p>
 * Self-skipping when ffmpeg is not installed, the same courtesy the video4j-backed suites extend via {@code assumeVideo4j()} - the node's image path and
 * all of its arithmetic remain covered on a machine without it. The fixture clip is generated by ffmpeg itself ({@code lavfi}), so nothing binary is
 * checked in.
 * </p>
 */
class WatermarkNodeVideoTest {

	private static final SHA512 HASH = SHA512.fromString(
		"a1c22b994c59d9cf2b48e549b1e24666636045930d3da7c1acb299d1c3b7f931f94aae41edda2c2b207a36e10f8bcb8d45223e54878f5b316e7ce3b6bc019629");

	private static final int WIDTH = 320;
	private static final int HEIGHT = 240;

	@TempDir
	File tempDir;

	private CortexOptions cortexOptions;
	private FfmpegRunner runner;
	private StubLoomMedia media;
	private String markBase64;

	@BeforeEach
	void setup() throws Exception {
		runner = new FfmpegRunner("ffmpeg", "ffprobe", 120_000);
		assumeTrue(runner.isAvailable(), "ffmpeg is not installed - skipping the watermark video path");

		cortexOptions = new CortexOptions().setMetaPath(tempDir.toPath());
		markBase64 = WatermarkFixtures.markBase64(64, 64);

		File clip = new File(tempDir, "clip.mp4");
		generateClip(clip);
		media = new StubLoomMedia(clip.getAbsolutePath(), true, false, false, false);
		media.setSHA512(HASH);
	}

	private WatermarkNodeOptions options() {
		// ultrafast: this test cares that the overlay was muxed in, not how well it compressed.
		return new WatermarkNodeOptions().setWatermarkBase64(markBase64).setVideoPreset("ultrafast");
	}

	private WatermarkNode node(WatermarkNodeOptions options) {
		return new WatermarkNode(null, cortexOptions, options);
	}

	@Test
	void testProbeReadsTheCodedDimensions() throws Exception {
		VideoDimensions dimensions = runner.probe(Path.of(media.absolutePath()));
		assertEquals(WIDTH, dimensions.width());
		assertEquals(HEIGHT, dimensions.height());
	}

	@Test
	void testProbeFailsOnAFileThatIsNotAVideo() throws Exception {
		Path text = tempDir.toPath().resolve("notes.txt");
		Files.writeString(text, "not a video");
		org.junit.jupiter.api.Assertions.assertThrows(java.io.IOException.class, () -> runner.probe(text));
	}

	@Test
	void testWritesAWatermarkedClipPreservingDimensionsAndAudio() throws Exception {
		NodeResult result = node(options()).process(NodeContext.create(media));
		assertThat(result).isSuccess();

		String outPath = result.get(WatermarkNode.OUT_VIDEO);
		assertNotNull(outPath, "the node should emit the marked video path");
		assertEquals("DONE", result.get(WatermarkNode.OUT_FLAG));
		assertNull(result.get(WatermarkNode.OUT_IMAGE), "the image port must stay empty for a video item");

		Path marked = Path.of(outPath);
		assertTrue(Files.exists(marked), "the clip should be written to the watermark_bin cache");
		assertTrue(marked.startsWith(tempDir.toPath().resolve("watermark_bin")), "the clip should live under metaPath/watermark_bin");
		assertTrue(outPath.endsWith(".mp4"), "the source container extension must be preserved but path was " + outPath);
		assertTrue(Files.size(marked) > 0);

		// The overlay must not have resized the picture.
		VideoDimensions dimensions = runner.probe(marked);
		assertEquals(WIDTH, dimensions.width());
		assertEquals(HEIGHT, dimensions.height());

		// The audio track must survive. `-c:a copy` means it is the same stream, not a re-encode.
		assertEquals("aac", streamCodec(marked, "a:0"), "the audio stream should be copied through untouched");
	}

	@Test
	void testNoTemporaryFilesAreLeftBehind() throws Exception {
		NodeResult result = node(options()).process(NodeContext.create(media));
		assertThat(result).isSuccess();

		Path artifact = Path.of(result.get(WatermarkNode.OUT_VIDEO));
		try (var entries = Files.list(artifact.getParent())) {
			List<String> names = entries.map(p -> p.getFileName().toString()).toList();
			assertEquals(List.of(artifact.getFileName().toString()), names,
				"the .part and .overlay.png working files should both be cleaned up");
		}
	}

	@Test
	void testSecondRunIsServedFromTheLocalCache() throws Exception {
		WatermarkNode node = node(options());
		NodeResult first = node.process(NodeContext.create(media));
		assertThat(first).isSuccess();

		// NodeResult carries no origin, so a cache hit is not directly observable. Overwrite the artifact with a sentinel: a re-encode is the most
		// expensive thing this node does, and it must not repeat it.
		Path artifact = Path.of(first.get(WatermarkNode.OUT_VIDEO));
		Files.writeString(artifact, "sentinel");

		NodeResult second = node.process(NodeContext.create(media));
		assertThat(second).isSuccess();
		assertEquals(first.get(WatermarkNode.OUT_VIDEO), second.get(WatermarkNode.OUT_VIDEO));
		assertEquals("sentinel", Files.readString(artifact), "the second run should not have re-encoded the clip");
	}

	@Test
	void testAMissingFfmpegFailsLoudlyRatherThanSkipping() {
		// A skip would read as "this clip needed no watermark" and quietly ship unmarked video. The operator has to see that the worker cannot do the job.
		NodeResult result = node(options().setFfmpegPath("definitely-not-ffmpeg")).process(NodeContext.create(media));
		assertThat(result).isFailed();
		assertEquals("FAILED", result.get(WatermarkNode.OUT_FLAG));
		assertTrue(result.getMessage() != null && result.getMessage().contains("ffmpeg"),
			"the failure should name ffmpeg so the cause is obvious, but was: " + result.getMessage());
	}

	/**
	 * Generate a short clip <em>with</em> an audio track, so the audio-copy assertion has something to assert on.
	 */
	private void generateClip(File target) throws Exception {
		exec(List.of("ffmpeg", "-nostdin", "-hide_banner", "-loglevel", "error", "-y",
			"-f", "lavfi", "-i", "testsrc=size=" + WIDTH + "x" + HEIGHT + ":rate=10:duration=1",
			"-f", "lavfi", "-i", "anullsrc=channel_layout=stereo:sample_rate=44100:duration=1",
			"-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
			"-c:a", "aac", "-shortest",
			target.getAbsolutePath()));
	}

	private String streamCodec(Path video, String stream) throws Exception {
		return exec(List.of("ffprobe", "-v", "error", "-select_streams", stream,
			"-show_entries", "stream=codec_name", "-of", "csv=p=0", video.toString())).trim();
	}

	private String exec(List<String> command) throws Exception {
		Process process = new ProcessBuilder(command).redirectErrorStream(true).start();
		String output = new String(process.getInputStream().readAllBytes());
		assertTrue(process.waitFor(120, TimeUnit.SECONDS), "the fixture command timed out: " + command);
		assertEquals(0, process.exitValue(), "the fixture command failed: " + command + "\n" + output);
		return output;
	}
}
