/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.converter.JsonObjectConverter;
import io.metaloom.loom.db.jooq.tables.records.JooqPipelineRecord;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqPipeline extends TableImpl<JooqPipelineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pipeline</code>
     */
    public static final JooqPipeline PIPELINE = new JooqPipeline();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqPipelineRecord> getRecordType() {
        return JooqPipelineRecord.class;
    }

    /**
     * The column <code>public.pipeline.uuid</code>.
     */
    public final TableField<JooqPipelineRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuidv7()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.pipeline.meta</code>.
     */
    public final TableField<JooqPipelineRecord, JsonObject> META = createField(DSL.name("meta"), SQLDataType.JSONB, this, "", new JsonObjectConverter());

    /**
     * The column <code>public.pipeline.created</code>.
     */
    public final TableField<JooqPipelineRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.pipeline.creator_uuid</code>.
     */
    public final TableField<JooqPipelineRecord, java.util.UUID> CREATOR_UUID = createField(DSL.name("creator_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.pipeline.edited</code>.
     */
    public final TableField<JooqPipelineRecord, LocalDateTime> EDITED = createField(DSL.name("edited"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.pipeline.editor_uuid</code>.
     */
    public final TableField<JooqPipelineRecord, java.util.UUID> EDITOR_UUID = createField(DSL.name("editor_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.pipeline.latest_version_uuid</code>. Reference to
     * the latest pipeline_version record
     */
    public final TableField<JooqPipelineRecord, java.util.UUID> LATEST_VERSION_UUID = createField(DSL.name("latest_version_uuid"), SQLDataType.UUID, this, "Reference to the latest pipeline_version record");

    private JooqPipeline(Name alias, Table<JooqPipelineRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqPipeline(Name alias, Table<JooqPipelineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.pipeline</code> table reference
     */
    public JooqPipeline(String alias) {
        this(DSL.name(alias), PIPELINE);
    }

    /**
     * Create an aliased <code>public.pipeline</code> table reference
     */
    public JooqPipeline(Name alias) {
        this(alias, PIPELINE);
    }

    /**
     * Create a <code>public.pipeline</code> table reference
     */
    public JooqPipeline() {
        this(DSL.name("pipeline"), null);
    }

    public <O extends Record> JooqPipeline(Table<O> child, ForeignKey<O, JooqPipelineRecord> key) {
        super(child, key, PIPELINE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public UniqueKey<JooqPipelineRecord> getPrimaryKey() {
        return Keys.PIPELINE_PKEY;
    }

    @Override
    public List<ForeignKey<JooqPipelineRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PIPELINE__PIPELINE_CREATOR_UUID_FKEY, Keys.PIPELINE__PIPELINE_EDITOR_UUID_FKEY, Keys.PIPELINE__PIPELINE_LATEST_VERSION_UUID_FKEY);
    }

    private transient JooqUser _pipelineCreatorUuidFkey;
    private transient JooqUser _pipelineEditorUuidFkey;
    private transient JooqPipelineVersion _pipelineVersion;

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>pipeline_creator_uuid_fkey</code> key.
     */
    public JooqUser pipelineCreatorUuidFkey() {
        if (_pipelineCreatorUuidFkey == null)
            _pipelineCreatorUuidFkey = new JooqUser(this, Keys.PIPELINE__PIPELINE_CREATOR_UUID_FKEY);

        return _pipelineCreatorUuidFkey;
    }

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>pipeline_editor_uuid_fkey</code> key.
     */
    public JooqUser pipelineEditorUuidFkey() {
        if (_pipelineEditorUuidFkey == null)
            _pipelineEditorUuidFkey = new JooqUser(this, Keys.PIPELINE__PIPELINE_EDITOR_UUID_FKEY);

        return _pipelineEditorUuidFkey;
    }

    /**
     * Get the implicit join path to the <code>public.pipeline_version</code>
     * table.
     */
    public JooqPipelineVersion pipelineVersion() {
        if (_pipelineVersion == null)
            _pipelineVersion = new JooqPipelineVersion(this, Keys.PIPELINE__PIPELINE_LATEST_VERSION_UUID_FKEY);

        return _pipelineVersion;
    }

    @Override
    public JooqPipeline as(String alias) {
        return new JooqPipeline(DSL.name(alias), this);
    }

    @Override
    public JooqPipeline as(Name alias) {
        return new JooqPipeline(alias, this);
    }

    @Override
    public JooqPipeline as(Table<?> alias) {
        return new JooqPipeline(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqPipeline rename(String name) {
        return new JooqPipeline(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqPipeline rename(Name name) {
        return new JooqPipeline(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqPipeline rename(Table<?> name) {
        return new JooqPipeline(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<java.util.UUID, JsonObject, LocalDateTime, java.util.UUID, LocalDateTime, java.util.UUID, java.util.UUID> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super java.util.UUID, ? super JsonObject, ? super LocalDateTime, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super java.util.UUID, ? super JsonObject, ? super LocalDateTime, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
