/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.converter.JsonObjectConverter;
import io.metaloom.loom.db.jooq.tables.records.JooqPersonRecord;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqPerson extends TableImpl<JooqPersonRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.person</code>
     */
    public static final JooqPerson PERSON = new JooqPerson();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqPersonRecord> getRecordType() {
        return JooqPersonRecord.class;
    }

    /**
     * The column <code>public.person.uuid</code>.
     */
    public final TableField<JooqPersonRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.person.alias</code>. Display alias for the person
     */
    public final TableField<JooqPersonRecord, String> ALIAS = createField(DSL.name("alias"), SQLDataType.VARCHAR, this, "Display alias for the person");

    /**
     * The column <code>public.person.firstname</code>. First name
     */
    public final TableField<JooqPersonRecord, String> FIRSTNAME = createField(DSL.name("firstname"), SQLDataType.VARCHAR, this, "First name");

    /**
     * The column <code>public.person.lastname</code>. Last name
     */
    public final TableField<JooqPersonRecord, String> LASTNAME = createField(DSL.name("lastname"), SQLDataType.VARCHAR, this, "Last name");

    /**
     * The column <code>public.person.meta</code>. Custom meta properties
     */
    public final TableField<JooqPersonRecord, JsonObject> META = createField(DSL.name("meta"), SQLDataType.JSONB, this, "Custom meta properties", new JsonObjectConverter());

    /**
     * The column <code>public.person.primary_image_uuid</code>. UUID of the
     * primary gallery image
     */
    public final TableField<JooqPersonRecord, java.util.UUID> PRIMARY_IMAGE_UUID = createField(DSL.name("primary_image_uuid"), SQLDataType.UUID, this, "UUID of the primary gallery image");

    /**
     * The column <code>public.person.created</code>.
     */
    public final TableField<JooqPersonRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.person.creator_uuid</code>.
     */
    public final TableField<JooqPersonRecord, java.util.UUID> CREATOR_UUID = createField(DSL.name("creator_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.person.edited</code>.
     */
    public final TableField<JooqPersonRecord, LocalDateTime> EDITED = createField(DSL.name("edited"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.person.editor_uuid</code>.
     */
    public final TableField<JooqPersonRecord, java.util.UUID> EDITOR_UUID = createField(DSL.name("editor_uuid"), SQLDataType.UUID.nullable(false), this, "");

    private JooqPerson(Name alias, Table<JooqPersonRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqPerson(Name alias, Table<JooqPersonRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.person</code> table reference
     */
    public JooqPerson(String alias) {
        this(DSL.name(alias), PERSON);
    }

    /**
     * Create an aliased <code>public.person</code> table reference
     */
    public JooqPerson(Name alias) {
        this(alias, PERSON);
    }

    /**
     * Create a <code>public.person</code> table reference
     */
    public JooqPerson() {
        this(DSL.name("person"), null);
    }

    public <O extends Record> JooqPerson(Table<O> child, ForeignKey<O, JooqPersonRecord> key) {
        super(child, key, PERSON);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public UniqueKey<JooqPersonRecord> getPrimaryKey() {
        return Keys.PERSON_PKEY;
    }

    @Override
    public List<ForeignKey<JooqPersonRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PERSON__PERSON_CREATOR_UUID_FKEY, Keys.PERSON__PERSON_EDITOR_UUID_FKEY);
    }

    private transient JooqUser _personCreatorUuidFkey;
    private transient JooqUser _personEditorUuidFkey;

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>person_creator_uuid_fkey</code> key.
     */
    public JooqUser personCreatorUuidFkey() {
        if (_personCreatorUuidFkey == null)
            _personCreatorUuidFkey = new JooqUser(this, Keys.PERSON__PERSON_CREATOR_UUID_FKEY);

        return _personCreatorUuidFkey;
    }

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>person_editor_uuid_fkey</code> key.
     */
    public JooqUser personEditorUuidFkey() {
        if (_personEditorUuidFkey == null)
            _personEditorUuidFkey = new JooqUser(this, Keys.PERSON__PERSON_EDITOR_UUID_FKEY);

        return _personEditorUuidFkey;
    }

    @Override
    public JooqPerson as(String alias) {
        return new JooqPerson(DSL.name(alias), this);
    }

    @Override
    public JooqPerson as(Name alias) {
        return new JooqPerson(alias, this);
    }

    @Override
    public JooqPerson as(Table<?> alias) {
        return new JooqPerson(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqPerson rename(String name) {
        return new JooqPerson(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqPerson rename(Name name) {
        return new JooqPerson(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqPerson rename(Table<?> name) {
        return new JooqPerson(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<java.util.UUID, String, String, String, JsonObject, java.util.UUID, LocalDateTime, java.util.UUID, LocalDateTime, java.util.UUID> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super java.util.UUID, ? super String, ? super String, ? super String, ? super JsonObject, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super java.util.UUID, ? super String, ? super String, ? super String, ? super JsonObject, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
