/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.Indexes;
import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.enums.JooqLoomPermission;
import io.metaloom.loom.db.jooq.tables.records.JooqTokenPermissionRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTokenPermission extends TableImpl<JooqTokenPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.token_permission</code>
     */
    public static final JooqTokenPermission TOKEN_PERMISSION = new JooqTokenPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqTokenPermissionRecord> getRecordType() {
        return JooqTokenPermissionRecord.class;
    }

    /**
     * The column <code>public.token_permission.token_uuid</code>.
     */
    public final TableField<JooqTokenPermissionRecord, UUID> TOKEN_UUID = createField(DSL.name("token_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.token_permission.resource</code>.
     */
    public final TableField<JooqTokenPermissionRecord, String> RESOURCE = createField(DSL.name("resource"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.token_permission.permission</code>. Permission
     * granted / granted to the resource
     */
    public final TableField<JooqTokenPermissionRecord, JooqLoomPermission> PERMISSION = createField(DSL.name("permission"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(io.metaloom.loom.db.jooq.enums.JooqLoomPermission.class), this, "Permission granted / granted to the resource");

    private JooqTokenPermission(Name alias, Table<JooqTokenPermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqTokenPermission(Name alias, Table<JooqTokenPermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.token_permission</code> table reference
     */
    public JooqTokenPermission(String alias) {
        this(DSL.name(alias), TOKEN_PERMISSION);
    }

    /**
     * Create an aliased <code>public.token_permission</code> table reference
     */
    public JooqTokenPermission(Name alias) {
        this(alias, TOKEN_PERMISSION);
    }

    /**
     * Create a <code>public.token_permission</code> table reference
     */
    public JooqTokenPermission() {
        this(DSL.name("token_permission"), null);
    }

    public <O extends Record> JooqTokenPermission(Table<O> child, ForeignKey<O, JooqTokenPermissionRecord> key) {
        super(child, key, TOKEN_PERMISSION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TOKEN_PERMISSION_TOKEN_UUID_RESOURCE_PERMISSION_IDX);
    }

    @Override
    public UniqueKey<JooqTokenPermissionRecord> getPrimaryKey() {
        return Keys.TOKEN_PERMISSION_PKEY;
    }

    @Override
    public List<ForeignKey<JooqTokenPermissionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TOKEN_PERMISSION__TOKEN_PERMISSION_TOKEN_UUID_FKEY);
    }

    private transient JooqToken _token;

    /**
     * Get the implicit join path to the <code>public.token</code> table.
     */
    public JooqToken token() {
        if (_token == null)
            _token = new JooqToken(this, Keys.TOKEN_PERMISSION__TOKEN_PERMISSION_TOKEN_UUID_FKEY);

        return _token;
    }

    @Override
    public JooqTokenPermission as(String alias) {
        return new JooqTokenPermission(DSL.name(alias), this);
    }

    @Override
    public JooqTokenPermission as(Name alias) {
        return new JooqTokenPermission(alias, this);
    }

    @Override
    public JooqTokenPermission as(Table<?> alias) {
        return new JooqTokenPermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqTokenPermission rename(String name) {
        return new JooqTokenPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqTokenPermission rename(Name name) {
        return new JooqTokenPermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqTokenPermission rename(Table<?> name) {
        return new JooqTokenPermission(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, JooqLoomPermission> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UUID, ? super String, ? super JooqLoomPermission, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UUID, ? super String, ? super JooqLoomPermission, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
