/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.Indexes;
import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.converter.JsonObjectConverter;
import io.metaloom.loom.db.jooq.tables.records.JooqPipelineVersionRecord;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function12;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Version history of pipeline definitions
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqPipelineVersion extends TableImpl<JooqPipelineVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pipeline_version</code>
     */
    public static final JooqPipelineVersion PIPELINE_VERSION = new JooqPipelineVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqPipelineVersionRecord> getRecordType() {
        return JooqPipelineVersionRecord.class;
    }

    /**
     * The column <code>public.pipeline_version.uuid</code>.
     */
    public final TableField<JooqPipelineVersionRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.pipeline_version.pipeline_uuid</code>. Reference
     * to the pipeline
     */
    public final TableField<JooqPipelineVersionRecord, java.util.UUID> PIPELINE_UUID = createField(DSL.name("pipeline_uuid"), SQLDataType.UUID.nullable(false), this, "Reference to the pipeline");

    /**
     * The column <code>public.pipeline_version.version_number</code>.
     * Sequential version number (1, 2, 3, ...)
     */
    public final TableField<JooqPipelineVersionRecord, Integer> VERSION_NUMBER = createField(DSL.name("version_number"), SQLDataType.INTEGER.nullable(false), this, "Sequential version number (1, 2, 3, ...)");

    /**
     * The column <code>public.pipeline_version.name</code>. Pipeline name at
     * this version
     */
    public final TableField<JooqPipelineVersionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "Pipeline name at this version");

    /**
     * The column <code>public.pipeline_version.description</code>. Pipeline
     * description at this version
     */
    public final TableField<JooqPipelineVersionRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR, this, "Pipeline description at this version");

    /**
     * The column <code>public.pipeline_version.definition</code>. Pipeline
     * definition JSON at this version
     */
    public final TableField<JooqPipelineVersionRecord, JSONB> DEFINITION = createField(DSL.name("definition"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field("'{}'::jsonb", SQLDataType.JSONB)), this, "Pipeline definition JSON at this version");

    /**
     * The column <code>public.pipeline_version.enabled</code>. Pipeline enabled
     * state at this version
     */
    public final TableField<JooqPipelineVersionRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("true", SQLDataType.BOOLEAN)), this, "Pipeline enabled state at this version");

    /**
     * The column <code>public.pipeline_version.priority</code>. Pipeline
     * priority at this version
     */
    public final TableField<JooqPipelineVersionRecord, Integer> PRIORITY = createField(DSL.name("priority"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "Pipeline priority at this version");

    /**
     * The column <code>public.pipeline_version.dry_run</code>. Pipeline dry_run
     * state at this version
     */
    public final TableField<JooqPipelineVersionRecord, Boolean> DRY_RUN = createField(DSL.name("dry_run"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "Pipeline dry_run state at this version");

    /**
     * The column <code>public.pipeline_version.meta</code>. Additional metadata
     * at this version
     */
    public final TableField<JooqPipelineVersionRecord, JsonObject> META = createField(DSL.name("meta"), SQLDataType.JSONB, this, "Additional metadata at this version", new JsonObjectConverter());

    /**
     * The column <code>public.pipeline_version.created</code>. When this
     * version was created
     */
    public final TableField<JooqPipelineVersionRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "When this version was created");

    /**
     * The column <code>public.pipeline_version.creator_uuid</code>. User who
     * created this version
     */
    public final TableField<JooqPipelineVersionRecord, java.util.UUID> CREATOR_UUID = createField(DSL.name("creator_uuid"), SQLDataType.UUID.nullable(false), this, "User who created this version");

    private JooqPipelineVersion(Name alias, Table<JooqPipelineVersionRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqPipelineVersion(Name alias, Table<JooqPipelineVersionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Version history of pipeline definitions"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.pipeline_version</code> table reference
     */
    public JooqPipelineVersion(String alias) {
        this(DSL.name(alias), PIPELINE_VERSION);
    }

    /**
     * Create an aliased <code>public.pipeline_version</code> table reference
     */
    public JooqPipelineVersion(Name alias) {
        this(alias, PIPELINE_VERSION);
    }

    /**
     * Create a <code>public.pipeline_version</code> table reference
     */
    public JooqPipelineVersion() {
        this(DSL.name("pipeline_version"), null);
    }

    public <O extends Record> JooqPipelineVersion(Table<O> child, ForeignKey<O, JooqPipelineVersionRecord> key) {
        super(child, key, PIPELINE_VERSION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PIPELINE_VERSION_PIPELINE_UUID, Indexes.IDX_PIPELINE_VERSION_VERSION_NUMBER);
    }

    @Override
    public UniqueKey<JooqPipelineVersionRecord> getPrimaryKey() {
        return Keys.PIPELINE_VERSION_PKEY;
    }

    @Override
    public List<UniqueKey<JooqPipelineVersionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PIPELINE_VERSION_UNIQUE_VERSION);
    }

    @Override
    public List<ForeignKey<JooqPipelineVersionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PIPELINE_VERSION__PIPELINE_VERSION_PIPELINE_UUID_FKEY, Keys.PIPELINE_VERSION__PIPELINE_VERSION_CREATOR_UUID_FKEY);
    }

    private transient JooqPipeline _pipeline;
    private transient JooqUser _user;

    /**
     * Get the implicit join path to the <code>public.pipeline</code> table.
     */
    public JooqPipeline pipeline() {
        if (_pipeline == null)
            _pipeline = new JooqPipeline(this, Keys.PIPELINE_VERSION__PIPELINE_VERSION_PIPELINE_UUID_FKEY);

        return _pipeline;
    }

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public JooqUser user() {
        if (_user == null)
            _user = new JooqUser(this, Keys.PIPELINE_VERSION__PIPELINE_VERSION_CREATOR_UUID_FKEY);

        return _user;
    }

    @Override
    public JooqPipelineVersion as(String alias) {
        return new JooqPipelineVersion(DSL.name(alias), this);
    }

    @Override
    public JooqPipelineVersion as(Name alias) {
        return new JooqPipelineVersion(alias, this);
    }

    @Override
    public JooqPipelineVersion as(Table<?> alias) {
        return new JooqPipelineVersion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqPipelineVersion rename(String name) {
        return new JooqPipelineVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqPipelineVersion rename(Name name) {
        return new JooqPipelineVersion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqPipelineVersion rename(Table<?> name) {
        return new JooqPipelineVersion(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<java.util.UUID, java.util.UUID, Integer, String, String, JSONB, Boolean, Integer, Boolean, JsonObject, LocalDateTime, java.util.UUID> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function12<? super java.util.UUID, ? super java.util.UUID, ? super Integer, ? super String, ? super String, ? super JSONB, ? super Boolean, ? super Integer, ? super Boolean, ? super JsonObject, ? super LocalDateTime, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function12<? super java.util.UUID, ? super java.util.UUID, ? super Integer, ? super String, ? super String, ? super JSONB, ? super Boolean, ? super Integer, ? super Boolean, ? super JsonObject, ? super LocalDateTime, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
