/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.Indexes;
import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.enums.JooqLoomPermission;
import io.metaloom.loom.db.jooq.tables.records.JooqRolePermissionRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqRolePermission extends TableImpl<JooqRolePermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.role_permission</code>
     */
    public static final JooqRolePermission ROLE_PERMISSION = new JooqRolePermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqRolePermissionRecord> getRecordType() {
        return JooqRolePermissionRecord.class;
    }

    /**
     * The column <code>public.role_permission.role_uuid</code>.
     */
    public final TableField<JooqRolePermissionRecord, UUID> ROLE_UUID = createField(DSL.name("role_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.role_permission.resource</code>.
     */
    public final TableField<JooqRolePermissionRecord, String> RESOURCE = createField(DSL.name("resource"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.role_permission.permission</code>. Permission
     * granted / granted to the resource
     */
    public final TableField<JooqRolePermissionRecord, JooqLoomPermission> PERMISSION = createField(DSL.name("permission"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(io.metaloom.loom.db.jooq.enums.JooqLoomPermission.class), this, "Permission granted / granted to the resource");

    private JooqRolePermission(Name alias, Table<JooqRolePermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqRolePermission(Name alias, Table<JooqRolePermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.role_permission</code> table reference
     */
    public JooqRolePermission(String alias) {
        this(DSL.name(alias), ROLE_PERMISSION);
    }

    /**
     * Create an aliased <code>public.role_permission</code> table reference
     */
    public JooqRolePermission(Name alias) {
        this(alias, ROLE_PERMISSION);
    }

    /**
     * Create a <code>public.role_permission</code> table reference
     */
    public JooqRolePermission() {
        this(DSL.name("role_permission"), null);
    }

    public <O extends Record> JooqRolePermission(Table<O> child, ForeignKey<O, JooqRolePermissionRecord> key) {
        super(child, key, ROLE_PERMISSION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ROLE_PERMISSION_ROLE_UUID_RESOURCE_PERMISSION_IDX);
    }

    @Override
    public UniqueKey<JooqRolePermissionRecord> getPrimaryKey() {
        return Keys.ROLE_PERMISSION_PKEY;
    }

    @Override
    public List<ForeignKey<JooqRolePermissionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ROLE_PERMISSION__ROLE_PERMISSION_ROLE_UUID_FKEY);
    }

    private transient JooqRole _role;

    /**
     * Get the implicit join path to the <code>public.role</code> table.
     */
    public JooqRole role() {
        if (_role == null)
            _role = new JooqRole(this, Keys.ROLE_PERMISSION__ROLE_PERMISSION_ROLE_UUID_FKEY);

        return _role;
    }

    @Override
    public JooqRolePermission as(String alias) {
        return new JooqRolePermission(DSL.name(alias), this);
    }

    @Override
    public JooqRolePermission as(Name alias) {
        return new JooqRolePermission(alias, this);
    }

    @Override
    public JooqRolePermission as(Table<?> alias) {
        return new JooqRolePermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqRolePermission rename(String name) {
        return new JooqRolePermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqRolePermission rename(Name name) {
        return new JooqRolePermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqRolePermission rename(Table<?> name) {
        return new JooqRolePermission(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, JooqLoomPermission> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UUID, ? super String, ? super JooqLoomPermission, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UUID, ? super String, ? super JooqLoomPermission, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
