/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.Indexes;
import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.converter.JsonObjectConverter;
import io.metaloom.loom.db.jooq.tables.records.JooqEmbeddingRecord;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Check;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function22;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row22;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Embedding vectors extracted from an asset. The geometry lives on the linked
 * detection - this table no longer carries a second, absolute-pixel copy of it.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqEmbedding extends TableImpl<JooqEmbeddingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.embedding</code>
     */
    public static final JooqEmbedding EMBEDDING = new JooqEmbedding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqEmbeddingRecord> getRecordType() {
        return JooqEmbeddingRecord.class;
    }

    /**
     * The column <code>public.embedding.uuid</code>.
     */
    public final TableField<JooqEmbeddingRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.embedding.asset_uuid</code>.
     */
    public final TableField<JooqEmbeddingRecord, java.util.UUID> ASSET_UUID = createField(DSL.name("asset_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.embedding.node_kind</code>.
     */
    public final TableField<JooqEmbeddingRecord, String> NODE_KIND = createField(DSL.name("node_kind"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.embedding.node_id</code>.
     */
    public final TableField<JooqEmbeddingRecord, String> NODE_ID = createField(DSL.name("node_id"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.embedding.producer_version</code>.
     */
    public final TableField<JooqEmbeddingRecord, String> PRODUCER_VERSION = createField(DSL.name("producer_version"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field("''::character varying", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.embedding.run_uuid</code>.
     */
    public final TableField<JooqEmbeddingRecord, java.util.UUID> RUN_UUID = createField(DSL.name("run_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.embedding.task_uuid</code>.
     */
    public final TableField<JooqEmbeddingRecord, java.util.UUID> TASK_UUID = createField(DSL.name("task_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.embedding.confidence</code>.
     */
    public final TableField<JooqEmbeddingRecord, Float> CONFIDENCE = createField(DSL.name("confidence"), SQLDataType.REAL, this, "");

    /**
     * The column <code>public.embedding.type</code>. Type of the embedding,
     * e.g. dlib_facemark, inspireface
     */
    public final TableField<JooqEmbeddingRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false), this, "Type of the embedding, e.g. dlib_facemark, inspireface");

    /**
     * The column <code>public.embedding.model</code>. Readable mirror of
     * producer_version
     */
    public final TableField<JooqEmbeddingRecord, String> MODEL = createField(DSL.name("model"), SQLDataType.VARCHAR, this, "Readable mirror of producer_version");

    /**
     * The column <code>public.embedding.dimensions</code>. Length of the
     * vector. Guards against comparing vectors from different models.
     */
    public final TableField<JooqEmbeddingRecord, Integer> DIMENSIONS = createField(DSL.name("dimensions"), SQLDataType.INTEGER.nullable(false), this, "Length of the vector. Guards against comparing vectors from different models.");

    /**
     * The column <code>public.embedding.vector</code>. Embedding vector as a
     * plain PostgreSQL array. OPEN DECISION: similarity search is either
     * pgvector in Postgres or an external index fed via vector_config. Until
     * that is decided this column is a staging buffer with no ANN index - see
     * spec/features/DB_SCHEMA_FEEDBACK.md section 4.2.
     */
    public final TableField<JooqEmbeddingRecord, Float[]> VECTOR = createField(DSL.name("vector"), SQLDataType.REAL.getArrayDataType(), this, "Embedding vector as a plain PostgreSQL array. OPEN DECISION: similarity search is either pgvector in Postgres or an external index fed via vector_config. Until that is decided this column is a staging buffer with no ANN index - see spec/features/DB_SCHEMA_FEEDBACK.md section 4.2.");

    /**
     * The column <code>public.embedding.detection_uuid</code>. The detection
     * this vector was computed from, when there is one. Whole-image and
     * audio-window embeddings leave it NULL.
     */
    public final TableField<JooqEmbeddingRecord, java.util.UUID> DETECTION_UUID = createField(DSL.name("detection_uuid"), SQLDataType.UUID, this, "The detection this vector was computed from, when there is one. Whole-image and audio-window embeddings leave it NULL.");

    /**
     * The column <code>public.embedding.frame_number</code>.
     */
    public final TableField<JooqEmbeddingRecord, Integer> FRAME_NUMBER = createField(DSL.name("frame_number"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.embedding.subject_index</code>. Ordinal of the
     * subject within the frame, used when there is no detection row to key on
     */
    public final TableField<JooqEmbeddingRecord, Integer> SUBJECT_INDEX = createField(DSL.name("subject_index"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "Ordinal of the subject within the frame, used when there is no detection row to key on");

    /**
     * The column <code>public.embedding.time_from</code>. Start of the window
     * this embedding covers, in milliseconds (audio/video)
     */
    public final TableField<JooqEmbeddingRecord, Long> TIME_FROM = createField(DSL.name("time_from"), SQLDataType.BIGINT, this, "Start of the window this embedding covers, in milliseconds (audio/video)");

    /**
     * The column <code>public.embedding.time_to</code>.
     */
    public final TableField<JooqEmbeddingRecord, Long> TIME_TO = createField(DSL.name("time_to"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.embedding.meta</code>.
     */
    public final TableField<JooqEmbeddingRecord, JsonObject> META = createField(DSL.name("meta"), SQLDataType.JSONB, this, "", new JsonObjectConverter());

    /**
     * The column <code>public.embedding.created</code>.
     */
    public final TableField<JooqEmbeddingRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.embedding.creator_uuid</code>. NULL when written
     * by a Cortex worker rather than a user
     */
    public final TableField<JooqEmbeddingRecord, java.util.UUID> CREATOR_UUID = createField(DSL.name("creator_uuid"), SQLDataType.UUID, this, "NULL when written by a Cortex worker rather than a user");

    /**
     * The column <code>public.embedding.edited</code>.
     */
    public final TableField<JooqEmbeddingRecord, LocalDateTime> EDITED = createField(DSL.name("edited"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.embedding.editor_uuid</code>.
     */
    public final TableField<JooqEmbeddingRecord, java.util.UUID> EDITOR_UUID = createField(DSL.name("editor_uuid"), SQLDataType.UUID, this, "");

    private JooqEmbedding(Name alias, Table<JooqEmbeddingRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqEmbedding(Name alias, Table<JooqEmbeddingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Embedding vectors extracted from an asset. The geometry lives on the linked detection - this table no longer carries a second, absolute-pixel copy of it."), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.embedding</code> table reference
     */
    public JooqEmbedding(String alias) {
        this(DSL.name(alias), EMBEDDING);
    }

    /**
     * Create an aliased <code>public.embedding</code> table reference
     */
    public JooqEmbedding(Name alias) {
        this(alias, EMBEDDING);
    }

    /**
     * Create a <code>public.embedding</code> table reference
     */
    public JooqEmbedding() {
        this(DSL.name("embedding"), null);
    }

    public <O extends Record> JooqEmbedding(Table<O> child, ForeignKey<O, JooqEmbeddingRecord> key) {
        super(child, key, EMBEDDING);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_EMBEDDING_ASSET_UUID, Indexes.IDX_EMBEDDING_DETECTION_UUID);
    }

    @Override
    public UniqueKey<JooqEmbeddingRecord> getPrimaryKey() {
        return Keys.EMBEDDING_PKEY;
    }

    @Override
    public List<UniqueKey<JooqEmbeddingRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.EMBEDDING_UNIQUE_KEY);
    }

    @Override
    public List<ForeignKey<JooqEmbeddingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EMBEDDING__EMBEDDING_ASSET_UUID_FKEY, Keys.EMBEDDING__EMBEDDING_RUN_UUID_FKEY, Keys.EMBEDDING__EMBEDDING_TASK_UUID_FKEY, Keys.EMBEDDING__EMBEDDING_DETECTION_UUID_FKEY, Keys.EMBEDDING__EMBEDDING_CREATOR_UUID_FKEY, Keys.EMBEDDING__EMBEDDING_EDITOR_UUID_FKEY);
    }

    private transient JooqAsset _asset;
    private transient JooqPipelineRun _pipelineRun;
    private transient JooqPipelineNodeTask _pipelineNodeTask;
    private transient JooqDetection _detection;
    private transient JooqUser _embeddingCreatorUuidFkey;
    private transient JooqUser _embeddingEditorUuidFkey;

    /**
     * Get the implicit join path to the <code>public.asset</code> table.
     */
    public JooqAsset asset() {
        if (_asset == null)
            _asset = new JooqAsset(this, Keys.EMBEDDING__EMBEDDING_ASSET_UUID_FKEY);

        return _asset;
    }

    /**
     * Get the implicit join path to the <code>public.pipeline_run</code> table.
     */
    public JooqPipelineRun pipelineRun() {
        if (_pipelineRun == null)
            _pipelineRun = new JooqPipelineRun(this, Keys.EMBEDDING__EMBEDDING_RUN_UUID_FKEY);

        return _pipelineRun;
    }

    /**
     * Get the implicit join path to the <code>public.pipeline_node_task</code>
     * table.
     */
    public JooqPipelineNodeTask pipelineNodeTask() {
        if (_pipelineNodeTask == null)
            _pipelineNodeTask = new JooqPipelineNodeTask(this, Keys.EMBEDDING__EMBEDDING_TASK_UUID_FKEY);

        return _pipelineNodeTask;
    }

    /**
     * Get the implicit join path to the <code>public.detection</code> table.
     */
    public JooqDetection detection() {
        if (_detection == null)
            _detection = new JooqDetection(this, Keys.EMBEDDING__EMBEDDING_DETECTION_UUID_FKEY);

        return _detection;
    }

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>embedding_creator_uuid_fkey</code> key.
     */
    public JooqUser embeddingCreatorUuidFkey() {
        if (_embeddingCreatorUuidFkey == null)
            _embeddingCreatorUuidFkey = new JooqUser(this, Keys.EMBEDDING__EMBEDDING_CREATOR_UUID_FKEY);

        return _embeddingCreatorUuidFkey;
    }

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>embedding_editor_uuid_fkey</code> key.
     */
    public JooqUser embeddingEditorUuidFkey() {
        if (_embeddingEditorUuidFkey == null)
            _embeddingEditorUuidFkey = new JooqUser(this, Keys.EMBEDDING__EMBEDDING_EDITOR_UUID_FKEY);

        return _embeddingEditorUuidFkey;
    }

    @Override
    public List<Check<JooqEmbeddingRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("embedding_range_check"), "(((time_to IS NULL) OR (time_from IS NULL) OR (time_to >= time_from)))", true)
        );
    }

    @Override
    public JooqEmbedding as(String alias) {
        return new JooqEmbedding(DSL.name(alias), this);
    }

    @Override
    public JooqEmbedding as(Name alias) {
        return new JooqEmbedding(alias, this);
    }

    @Override
    public JooqEmbedding as(Table<?> alias) {
        return new JooqEmbedding(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqEmbedding rename(String name) {
        return new JooqEmbedding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqEmbedding rename(Name name) {
        return new JooqEmbedding(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqEmbedding rename(Table<?> name) {
        return new JooqEmbedding(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row22 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row22<java.util.UUID, java.util.UUID, String, String, String, java.util.UUID, java.util.UUID, Float, String, String, Integer, Float[], java.util.UUID, Integer, Integer, Long, Long, JsonObject, LocalDateTime, java.util.UUID, LocalDateTime, java.util.UUID> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function22<? super java.util.UUID, ? super java.util.UUID, ? super String, ? super String, ? super String, ? super java.util.UUID, ? super java.util.UUID, ? super Float, ? super String, ? super String, ? super Integer, ? super Float[], ? super java.util.UUID, ? super Integer, ? super Integer, ? super Long, ? super Long, ? super JsonObject, ? super LocalDateTime, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function22<? super java.util.UUID, ? super java.util.UUID, ? super String, ? super String, ? super String, ? super java.util.UUID, ? super java.util.UUID, ? super Float, ? super String, ? super String, ? super Integer, ? super Float[], ? super java.util.UUID, ? super Integer, ? super Integer, ? super Long, ? super Long, ? super JsonObject, ? super LocalDateTime, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
