/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.converter.JsonObjectConverter;
import io.metaloom.loom.db.jooq.tables.records.JooqCortexInstanceRecord;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function13;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * A registered Cortex/processor worker, keyed by its stable node_id
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqCortexInstance extends TableImpl<JooqCortexInstanceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.cortex_instance</code>
     */
    public static final JooqCortexInstance CORTEX_INSTANCE = new JooqCortexInstance();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqCortexInstanceRecord> getRecordType() {
        return JooqCortexInstanceRecord.class;
    }

    /**
     * The column <code>public.cortex_instance.uuid</code>.
     */
    public final TableField<JooqCortexInstanceRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuidv7()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.cortex_instance.node_id</code>. Stable worker
     * identity used to reconcile the in-memory registry across reconnects
     */
    public final TableField<JooqCortexInstanceRecord, String> NODE_ID = createField(DSL.name("node_id"), SQLDataType.VARCHAR.nullable(false), this, "Stable worker identity used to reconcile the in-memory registry across reconnects");

    /**
     * The column <code>public.cortex_instance.name</code>. Human readable name
     * of the worker
     */
    public final TableField<JooqCortexInstanceRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR, this, "Human readable name of the worker");

    /**
     * The column <code>public.cortex_instance.host</code>. Host address of the
     * worker (e.g. 10.0.1.10:9090)
     */
    public final TableField<JooqCortexInstanceRecord, String> HOST = createField(DSL.name("host"), SQLDataType.VARCHAR, this, "Host address of the worker (e.g. 10.0.1.10:9090)");

    /**
     * The column <code>public.cortex_instance.priority</code>. Selection
     * priority (higher = preferred)
     */
    public final TableField<JooqCortexInstanceRecord, Integer> PRIORITY = createField(DSL.name("priority"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "Selection priority (higher = preferred)");

    /**
     * The column <code>public.cortex_instance.last_seen</code>. Timestamp of
     * the last registration/heartbeat
     */
    public final TableField<JooqCortexInstanceRecord, LocalDateTime> LAST_SEEN = createField(DSL.name("last_seen"), SQLDataType.LOCALDATETIME(6), this, "Timestamp of the last registration/heartbeat");

    /**
     * The column <code>public.cortex_instance.state</code>. Last known
     * processor state (e.g. ONLINE)
     */
    public final TableField<JooqCortexInstanceRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR, this, "Last known processor state (e.g. ONLINE)");

    /**
     * The column <code>public.cortex_instance.first_registered</code>. When
     * this worker first registered
     */
    public final TableField<JooqCortexInstanceRecord, LocalDateTime> FIRST_REGISTERED = createField(DSL.name("first_registered"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "When this worker first registered");

    /**
     * The column <code>public.cortex_instance.meta</code>.
     */
    public final TableField<JooqCortexInstanceRecord, JsonObject> META = createField(DSL.name("meta"), SQLDataType.JSONB, this, "", new JsonObjectConverter());

    /**
     * The column <code>public.cortex_instance.created</code>.
     */
    public final TableField<JooqCortexInstanceRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.cortex_instance.creator_uuid</code>.
     */
    public final TableField<JooqCortexInstanceRecord, java.util.UUID> CREATOR_UUID = createField(DSL.name("creator_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.cortex_instance.edited</code>.
     */
    public final TableField<JooqCortexInstanceRecord, LocalDateTime> EDITED = createField(DSL.name("edited"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.cortex_instance.editor_uuid</code>.
     */
    public final TableField<JooqCortexInstanceRecord, java.util.UUID> EDITOR_UUID = createField(DSL.name("editor_uuid"), SQLDataType.UUID, this, "");

    private JooqCortexInstance(Name alias, Table<JooqCortexInstanceRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqCortexInstance(Name alias, Table<JooqCortexInstanceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("A registered Cortex/processor worker, keyed by its stable node_id"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.cortex_instance</code> table reference
     */
    public JooqCortexInstance(String alias) {
        this(DSL.name(alias), CORTEX_INSTANCE);
    }

    /**
     * Create an aliased <code>public.cortex_instance</code> table reference
     */
    public JooqCortexInstance(Name alias) {
        this(alias, CORTEX_INSTANCE);
    }

    /**
     * Create a <code>public.cortex_instance</code> table reference
     */
    public JooqCortexInstance() {
        this(DSL.name("cortex_instance"), null);
    }

    public <O extends Record> JooqCortexInstance(Table<O> child, ForeignKey<O, JooqCortexInstanceRecord> key) {
        super(child, key, CORTEX_INSTANCE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public UniqueKey<JooqCortexInstanceRecord> getPrimaryKey() {
        return Keys.CORTEX_INSTANCE_PKEY;
    }

    @Override
    public List<UniqueKey<JooqCortexInstanceRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CORTEX_INSTANCE_NODE_ID_KEY);
    }

    @Override
    public List<ForeignKey<JooqCortexInstanceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CORTEX_INSTANCE__CORTEX_INSTANCE_CREATOR_UUID_FKEY, Keys.CORTEX_INSTANCE__CORTEX_INSTANCE_EDITOR_UUID_FKEY);
    }

    private transient JooqUser _cortexInstanceCreatorUuidFkey;
    private transient JooqUser _cortexInstanceEditorUuidFkey;

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>cortex_instance_creator_uuid_fkey</code> key.
     */
    public JooqUser cortexInstanceCreatorUuidFkey() {
        if (_cortexInstanceCreatorUuidFkey == null)
            _cortexInstanceCreatorUuidFkey = new JooqUser(this, Keys.CORTEX_INSTANCE__CORTEX_INSTANCE_CREATOR_UUID_FKEY);

        return _cortexInstanceCreatorUuidFkey;
    }

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>cortex_instance_editor_uuid_fkey</code> key.
     */
    public JooqUser cortexInstanceEditorUuidFkey() {
        if (_cortexInstanceEditorUuidFkey == null)
            _cortexInstanceEditorUuidFkey = new JooqUser(this, Keys.CORTEX_INSTANCE__CORTEX_INSTANCE_EDITOR_UUID_FKEY);

        return _cortexInstanceEditorUuidFkey;
    }

    @Override
    public JooqCortexInstance as(String alias) {
        return new JooqCortexInstance(DSL.name(alias), this);
    }

    @Override
    public JooqCortexInstance as(Name alias) {
        return new JooqCortexInstance(alias, this);
    }

    @Override
    public JooqCortexInstance as(Table<?> alias) {
        return new JooqCortexInstance(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqCortexInstance rename(String name) {
        return new JooqCortexInstance(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqCortexInstance rename(Name name) {
        return new JooqCortexInstance(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqCortexInstance rename(Table<?> name) {
        return new JooqCortexInstance(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<java.util.UUID, String, String, String, Integer, LocalDateTime, String, LocalDateTime, JsonObject, LocalDateTime, java.util.UUID, LocalDateTime, java.util.UUID> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function13<? super java.util.UUID, ? super String, ? super String, ? super String, ? super Integer, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super JsonObject, ? super LocalDateTime, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function13<? super java.util.UUID, ? super String, ? super String, ? super String, ? super Integer, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super JsonObject, ? super LocalDateTime, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
