/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.Indexes;
import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.converter.JsonObjectConverter;
import io.metaloom.loom.db.jooq.enums.JooqReviewStatus;
import io.metaloom.loom.db.jooq.tables.records.JooqDetectionRecord;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Object and face detections within assets. One row per detected instance,
 * keyed by (asset, producer, frame, ordinal) so a re-run replaces rather than
 * duplicates.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqDetection extends TableImpl<JooqDetectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.detection</code>
     */
    public static final JooqDetection DETECTION = new JooqDetection();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqDetectionRecord> getRecordType() {
        return JooqDetectionRecord.class;
    }

    /**
     * The column <code>public.detection.uuid</code>.
     */
    public final TableField<JooqDetectionRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.detection.asset_uuid</code>.
     */
    public final TableField<JooqDetectionRecord, java.util.UUID> ASSET_UUID = createField(DSL.name("asset_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.detection.node_kind</code>.
     */
    public final TableField<JooqDetectionRecord, String> NODE_KIND = createField(DSL.name("node_kind"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.detection.node_id</code>.
     */
    public final TableField<JooqDetectionRecord, String> NODE_ID = createField(DSL.name("node_id"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.detection.producer_version</code>.
     */
    public final TableField<JooqDetectionRecord, String> PRODUCER_VERSION = createField(DSL.name("producer_version"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field("''::character varying", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.detection.run_uuid</code>.
     */
    public final TableField<JooqDetectionRecord, java.util.UUID> RUN_UUID = createField(DSL.name("run_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.detection.task_uuid</code>.
     */
    public final TableField<JooqDetectionRecord, java.util.UUID> TASK_UUID = createField(DSL.name("task_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.detection.type</code>. Kind of detection, e.g.
     * facedetection, objectdetection
     */
    public final TableField<JooqDetectionRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false), this, "Kind of detection, e.g. facedetection, objectdetection");

    /**
     * The column <code>public.detection.label</code>. Detected class for object
     * detection, e.g. dog. Promoted out of meta so it can be indexed.
     */
    public final TableField<JooqDetectionRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR, this, "Detected class for object detection, e.g. dog. Promoted out of meta so it can be indexed.");

    /**
     * The column <code>public.detection.frame_number</code>. Frame index within
     * the media; 0 for images
     */
    public final TableField<JooqDetectionRecord, Integer> FRAME_NUMBER = createField(DSL.name("frame_number"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "Frame index within the media; 0 for images");

    /**
     * The column <code>public.detection.detection_index</code>. Ordinal of this
     * detection within the frame, starting at 0
     */
    public final TableField<JooqDetectionRecord, Integer> DETECTION_INDEX = createField(DSL.name("detection_index"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "Ordinal of this detection within the frame, starting at 0");

    /**
     * The column <code>public.detection.time_from</code>. Millisecond offset of
     * the frame, for video
     */
    public final TableField<JooqDetectionRecord, Long> TIME_FROM = createField(DSL.name("time_from"), SQLDataType.BIGINT, this, "Millisecond offset of the frame, for video");

    /**
     * The column <code>public.detection.bbox_x</code>. Bounding box X,
     * normalized 0-1. This is the single geometry convention; embedding no
     * longer carries a second one.
     */
    public final TableField<JooqDetectionRecord, Float> BBOX_X = createField(DSL.name("bbox_x"), SQLDataType.REAL.nullable(false).defaultValue(DSL.field("0", SQLDataType.REAL)), this, "Bounding box X, normalized 0-1. This is the single geometry convention; embedding no longer carries a second one.");

    /**
     * The column <code>public.detection.bbox_y</code>.
     */
    public final TableField<JooqDetectionRecord, Float> BBOX_Y = createField(DSL.name("bbox_y"), SQLDataType.REAL.nullable(false).defaultValue(DSL.field("0", SQLDataType.REAL)), this, "");

    /**
     * The column <code>public.detection.bbox_width</code>.
     */
    public final TableField<JooqDetectionRecord, Float> BBOX_WIDTH = createField(DSL.name("bbox_width"), SQLDataType.REAL.nullable(false).defaultValue(DSL.field("0", SQLDataType.REAL)), this, "");

    /**
     * The column <code>public.detection.bbox_height</code>.
     */
    public final TableField<JooqDetectionRecord, Float> BBOX_HEIGHT = createField(DSL.name("bbox_height"), SQLDataType.REAL.nullable(false).defaultValue(DSL.field("0", SQLDataType.REAL)), this, "");

    /**
     * The column <code>public.detection.confidence</code>. Detection
     * confidence, 0.0 - 1.0
     */
    public final TableField<JooqDetectionRecord, Float> CONFIDENCE = createField(DSL.name("confidence"), SQLDataType.REAL.nullable(false).defaultValue(DSL.field("0", SQLDataType.REAL)), this, "Detection confidence, 0.0 - 1.0");

    /**
     * The column <code>public.detection.meta</code>. Custom meta properties
     * (e.g. gender, age, face angle)
     */
    public final TableField<JooqDetectionRecord, JsonObject> META = createField(DSL.name("meta"), SQLDataType.JSONB, this, "Custom meta properties (e.g. gender, age, face angle)", new JsonObjectConverter());

    /**
     * The column <code>public.detection.created</code>.
     */
    public final TableField<JooqDetectionRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.detection.creator_uuid</code>. NULL when written
     * by a Cortex worker rather than a user
     */
    public final TableField<JooqDetectionRecord, java.util.UUID> CREATOR_UUID = createField(DSL.name("creator_uuid"), SQLDataType.UUID, this, "NULL when written by a Cortex worker rather than a user");

    /**
     * The column <code>public.detection.edited</code>.
     */
    public final TableField<JooqDetectionRecord, LocalDateTime> EDITED = createField(DSL.name("edited"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.detection.editor_uuid</code>.
     */
    public final TableField<JooqDetectionRecord, java.util.UUID> EDITOR_UUID = createField(DSL.name("editor_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.detection.status</code>. PENDING (awaiting
     * review), CONFIRMED (a human agreed with the detection) or REJECTED (a
     * false positive). Reset to PENDING by an upsert whose producer_version
     * differs from the stored one.
     */
    public final TableField<JooqDetectionRecord, JooqReviewStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field("'PENDING'::review_status", SQLDataType.VARCHAR)).asEnumDataType(io.metaloom.loom.db.jooq.enums.JooqReviewStatus.class), this, "PENDING (awaiting review), CONFIRMED (a human agreed with the detection) or REJECTED (a false positive). Reset to PENDING by an upsert whose producer_version differs from the stored one.");

    /**
     * The column <code>public.detection.reviewed_at</code>. When a human
     * decided. NULL while PENDING. Distinct from "edited", which the producing
     * node touches on every re-run.
     */
    public final TableField<JooqDetectionRecord, LocalDateTime> REVIEWED_AT = createField(DSL.name("reviewed_at"), SQLDataType.LOCALDATETIME(6), this, "When a human decided. NULL while PENDING. Distinct from \"edited\", which the producing node touches on every re-run.");

    /**
     * The column <code>public.detection.reviewer_uuid</code>. The user who
     * decided. Distinct from editor_uuid, which is machine-written provenance
     * (V2.47).
     */
    public final TableField<JooqDetectionRecord, java.util.UUID> REVIEWER_UUID = createField(DSL.name("reviewer_uuid"), SQLDataType.UUID, this, "The user who decided. Distinct from editor_uuid, which is machine-written provenance (V2.47).");

    /**
     * The column <code>public.detection.corrected_label</code>. The label a
     * reviewer supplied when the detection was right but its class was wrong.
     * "label" keeps what the model said, which is the training signal.
     */
    public final TableField<JooqDetectionRecord, String> CORRECTED_LABEL = createField(DSL.name("corrected_label"), SQLDataType.VARCHAR, this, "The label a reviewer supplied when the detection was right but its class was wrong. \"label\" keeps what the model said, which is the training signal.");

    private JooqDetection(Name alias, Table<JooqDetectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqDetection(Name alias, Table<JooqDetectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Object and face detections within assets. One row per detected instance, keyed by (asset, producer, frame, ordinal) so a re-run replaces rather than duplicates."), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.detection</code> table reference
     */
    public JooqDetection(String alias) {
        this(DSL.name(alias), DETECTION);
    }

    /**
     * Create an aliased <code>public.detection</code> table reference
     */
    public JooqDetection(Name alias) {
        this(alias, DETECTION);
    }

    /**
     * Create a <code>public.detection</code> table reference
     */
    public JooqDetection() {
        this(DSL.name("detection"), null);
    }

    public <O extends Record> JooqDetection(Table<O> child, ForeignKey<O, JooqDetectionRecord> key) {
        super(child, key, DETECTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_DETECTION_ASSET_UUID, Indexes.IDX_DETECTION_LABEL, Indexes.IDX_DETECTION_REVIEW, Indexes.IDX_DETECTION_STATUS_TYPE, Indexes.IDX_DETECTION_TYPE);
    }

    @Override
    public UniqueKey<JooqDetectionRecord> getPrimaryKey() {
        return Keys.DETECTION_PKEY;
    }

    @Override
    public List<UniqueKey<JooqDetectionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.DETECTION_UNIQUE_KEY);
    }

    @Override
    public List<ForeignKey<JooqDetectionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DETECTION__DETECTION_ASSET_UUID_FKEY, Keys.DETECTION__DETECTION_RUN_UUID_FKEY, Keys.DETECTION__DETECTION_TASK_UUID_FKEY, Keys.DETECTION__DETECTION_CREATOR_UUID_FKEY, Keys.DETECTION__DETECTION_EDITOR_UUID_FKEY, Keys.DETECTION__DETECTION_REVIEWER_UUID_FKEY);
    }

    private transient JooqAsset _asset;
    private transient JooqPipelineRun _pipelineRun;
    private transient JooqPipelineNodeTask _pipelineNodeTask;
    private transient JooqUser _detectionCreatorUuidFkey;
    private transient JooqUser _detectionEditorUuidFkey;
    private transient JooqUser _detectionReviewerUuidFkey;

    /**
     * Get the implicit join path to the <code>public.asset</code> table.
     */
    public JooqAsset asset() {
        if (_asset == null)
            _asset = new JooqAsset(this, Keys.DETECTION__DETECTION_ASSET_UUID_FKEY);

        return _asset;
    }

    /**
     * Get the implicit join path to the <code>public.pipeline_run</code> table.
     */
    public JooqPipelineRun pipelineRun() {
        if (_pipelineRun == null)
            _pipelineRun = new JooqPipelineRun(this, Keys.DETECTION__DETECTION_RUN_UUID_FKEY);

        return _pipelineRun;
    }

    /**
     * Get the implicit join path to the <code>public.pipeline_node_task</code>
     * table.
     */
    public JooqPipelineNodeTask pipelineNodeTask() {
        if (_pipelineNodeTask == null)
            _pipelineNodeTask = new JooqPipelineNodeTask(this, Keys.DETECTION__DETECTION_TASK_UUID_FKEY);

        return _pipelineNodeTask;
    }

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>detection_creator_uuid_fkey</code> key.
     */
    public JooqUser detectionCreatorUuidFkey() {
        if (_detectionCreatorUuidFkey == null)
            _detectionCreatorUuidFkey = new JooqUser(this, Keys.DETECTION__DETECTION_CREATOR_UUID_FKEY);

        return _detectionCreatorUuidFkey;
    }

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>detection_editor_uuid_fkey</code> key.
     */
    public JooqUser detectionEditorUuidFkey() {
        if (_detectionEditorUuidFkey == null)
            _detectionEditorUuidFkey = new JooqUser(this, Keys.DETECTION__DETECTION_EDITOR_UUID_FKEY);

        return _detectionEditorUuidFkey;
    }

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>detection_reviewer_uuid_fkey</code> key.
     */
    public JooqUser detectionReviewerUuidFkey() {
        if (_detectionReviewerUuidFkey == null)
            _detectionReviewerUuidFkey = new JooqUser(this, Keys.DETECTION__DETECTION_REVIEWER_UUID_FKEY);

        return _detectionReviewerUuidFkey;
    }

    @Override
    public JooqDetection as(String alias) {
        return new JooqDetection(DSL.name(alias), this);
    }

    @Override
    public JooqDetection as(Name alias) {
        return new JooqDetection(alias, this);
    }

    @Override
    public JooqDetection as(Table<?> alias) {
        return new JooqDetection(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqDetection rename(String name) {
        return new JooqDetection(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqDetection rename(Name name) {
        return new JooqDetection(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqDetection rename(Table<?> name) {
        return new JooqDetection(name.getQualifiedName(), null);
    }
}
