/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.tables.records.JooqChatSessionSkillRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Skill versions active for a chat session (pins skill_version.version_number)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqChatSessionSkill extends TableImpl<JooqChatSessionSkillRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.chat_session_skill</code>
     */
    public static final JooqChatSessionSkill CHAT_SESSION_SKILL = new JooqChatSessionSkill();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqChatSessionSkillRecord> getRecordType() {
        return JooqChatSessionSkillRecord.class;
    }

    /**
     * The column <code>public.chat_session_skill.session_uuid</code>.
     */
    public final TableField<JooqChatSessionSkillRecord, UUID> SESSION_UUID = createField(DSL.name("session_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.chat_session_skill.skill_uuid</code>.
     */
    public final TableField<JooqChatSessionSkillRecord, UUID> SKILL_UUID = createField(DSL.name("skill_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.chat_session_skill.skill_version</code>.
     */
    public final TableField<JooqChatSessionSkillRecord, Integer> SKILL_VERSION = createField(DSL.name("skill_version"), SQLDataType.INTEGER.nullable(false), this, "");

    private JooqChatSessionSkill(Name alias, Table<JooqChatSessionSkillRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqChatSessionSkill(Name alias, Table<JooqChatSessionSkillRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Skill versions active for a chat session (pins skill_version.version_number)"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.chat_session_skill</code> table reference
     */
    public JooqChatSessionSkill(String alias) {
        this(DSL.name(alias), CHAT_SESSION_SKILL);
    }

    /**
     * Create an aliased <code>public.chat_session_skill</code> table reference
     */
    public JooqChatSessionSkill(Name alias) {
        this(alias, CHAT_SESSION_SKILL);
    }

    /**
     * Create a <code>public.chat_session_skill</code> table reference
     */
    public JooqChatSessionSkill() {
        this(DSL.name("chat_session_skill"), null);
    }

    public <O extends Record> JooqChatSessionSkill(Table<O> child, ForeignKey<O, JooqChatSessionSkillRecord> key) {
        super(child, key, CHAT_SESSION_SKILL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public UniqueKey<JooqChatSessionSkillRecord> getPrimaryKey() {
        return Keys.CHAT_SESSION_SKILL_PKEY;
    }

    @Override
    public List<ForeignKey<JooqChatSessionSkillRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHAT_SESSION_SKILL__CHAT_SESSION_SKILL_SESSION_UUID_FKEY, Keys.CHAT_SESSION_SKILL__CHAT_SESSION_SKILL_SKILL_UUID_FKEY);
    }

    private transient JooqChatSession _chatSession;
    private transient JooqSkill _skill;

    /**
     * Get the implicit join path to the <code>public.chat_session</code> table.
     */
    public JooqChatSession chatSession() {
        if (_chatSession == null)
            _chatSession = new JooqChatSession(this, Keys.CHAT_SESSION_SKILL__CHAT_SESSION_SKILL_SESSION_UUID_FKEY);

        return _chatSession;
    }

    /**
     * Get the implicit join path to the <code>public.skill</code> table.
     */
    public JooqSkill skill() {
        if (_skill == null)
            _skill = new JooqSkill(this, Keys.CHAT_SESSION_SKILL__CHAT_SESSION_SKILL_SKILL_UUID_FKEY);

        return _skill;
    }

    @Override
    public JooqChatSessionSkill as(String alias) {
        return new JooqChatSessionSkill(DSL.name(alias), this);
    }

    @Override
    public JooqChatSessionSkill as(Name alias) {
        return new JooqChatSessionSkill(alias, this);
    }

    @Override
    public JooqChatSessionSkill as(Table<?> alias) {
        return new JooqChatSessionSkill(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqChatSessionSkill rename(String name) {
        return new JooqChatSessionSkill(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqChatSessionSkill rename(Name name) {
        return new JooqChatSessionSkill(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqChatSessionSkill rename(Table<?> name) {
        return new JooqChatSessionSkill(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UUID, ? super UUID, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UUID, ? super UUID, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
