/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.Indexes;
import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.converter.JsonObjectConverter;
import io.metaloom.loom.db.jooq.tables.records.JooqRoleRecord;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqRole extends TableImpl<JooqRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.role</code>
     */
    public static final JooqRole ROLE = new JooqRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqRoleRecord> getRecordType() {
        return JooqRoleRecord.class;
    }

    /**
     * The column <code>public.role.uuid</code>.
     */
    public final TableField<JooqRoleRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.role.name</code>.
     */
    public final TableField<JooqRoleRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.role.meta</code>. Custom meta properties to the
     * element
     */
    public final TableField<JooqRoleRecord, JsonObject> META = createField(DSL.name("meta"), SQLDataType.JSONB, this, "Custom meta properties to the element", new JsonObjectConverter());

    /**
     * The column <code>public.role.created</code>.
     */
    public final TableField<JooqRoleRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.role.creator_uuid</code>.
     */
    public final TableField<JooqRoleRecord, java.util.UUID> CREATOR_UUID = createField(DSL.name("creator_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.role.edited</code>.
     */
    public final TableField<JooqRoleRecord, LocalDateTime> EDITED = createField(DSL.name("edited"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.role.editor_uuid</code>.
     */
    public final TableField<JooqRoleRecord, java.util.UUID> EDITOR_UUID = createField(DSL.name("editor_uuid"), SQLDataType.UUID.nullable(false), this, "");

    private JooqRole(Name alias, Table<JooqRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqRole(Name alias, Table<JooqRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.role</code> table reference
     */
    public JooqRole(String alias) {
        this(DSL.name(alias), ROLE);
    }

    /**
     * Create an aliased <code>public.role</code> table reference
     */
    public JooqRole(Name alias) {
        this(alias, ROLE);
    }

    /**
     * Create a <code>public.role</code> table reference
     */
    public JooqRole() {
        this(DSL.name("role"), null);
    }

    public <O extends Record> JooqRole(Table<O> child, ForeignKey<O, JooqRoleRecord> key) {
        super(child, key, ROLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ROLE_NAME_IDX);
    }

    @Override
    public UniqueKey<JooqRoleRecord> getPrimaryKey() {
        return Keys.ROLE_PKEY;
    }

    @Override
    public List<UniqueKey<JooqRoleRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ROLE_NAME_KEY);
    }

    @Override
    public List<ForeignKey<JooqRoleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ROLE__ROLE_CREATOR_UUID_FKEY, Keys.ROLE__ROLE_EDITOR_UUID_FKEY);
    }

    private transient JooqUser _roleCreatorUuidFkey;
    private transient JooqUser _roleEditorUuidFkey;

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>role_creator_uuid_fkey</code> key.
     */
    public JooqUser roleCreatorUuidFkey() {
        if (_roleCreatorUuidFkey == null)
            _roleCreatorUuidFkey = new JooqUser(this, Keys.ROLE__ROLE_CREATOR_UUID_FKEY);

        return _roleCreatorUuidFkey;
    }

    /**
     * Get the implicit join path to the <code>public.user</code> table, via the
     * <code>role_editor_uuid_fkey</code> key.
     */
    public JooqUser roleEditorUuidFkey() {
        if (_roleEditorUuidFkey == null)
            _roleEditorUuidFkey = new JooqUser(this, Keys.ROLE__ROLE_EDITOR_UUID_FKEY);

        return _roleEditorUuidFkey;
    }

    @Override
    public JooqRole as(String alias) {
        return new JooqRole(DSL.name(alias), this);
    }

    @Override
    public JooqRole as(Name alias) {
        return new JooqRole(alias, this);
    }

    @Override
    public JooqRole as(Table<?> alias) {
        return new JooqRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqRole rename(String name) {
        return new JooqRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqRole rename(Name name) {
        return new JooqRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqRole rename(Table<?> name) {
        return new JooqRole(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<java.util.UUID, String, JsonObject, LocalDateTime, java.util.UUID, LocalDateTime, java.util.UUID> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super java.util.UUID, ? super String, ? super JsonObject, ? super LocalDateTime, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super java.util.UUID, ? super String, ? super JsonObject, ? super LocalDateTime, ? super java.util.UUID, ? super LocalDateTime, ? super java.util.UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
