/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.tables.records.JooqSearchTranscriptWindowsRecord;

import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqSearchTranscriptWindows extends TableImpl<JooqSearchTranscriptWindowsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.search_transcript_windows</code>
     */
    public static final JooqSearchTranscriptWindows SEARCH_TRANSCRIPT_WINDOWS = new JooqSearchTranscriptWindows();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqSearchTranscriptWindowsRecord> getRecordType() {
        return JooqSearchTranscriptWindowsRecord.class;
    }

    /**
     * The column <code>public.search_transcript_windows.window_index</code>.
     */
    public final TableField<JooqSearchTranscriptWindowsRecord, Integer> WINDOW_INDEX = createField(DSL.name("window_index"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.search_transcript_windows.time_from</code>.
     */
    public final TableField<JooqSearchTranscriptWindowsRecord, Long> TIME_FROM = createField(DSL.name("time_from"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.search_transcript_windows.body</code>.
     */
    public final TableField<JooqSearchTranscriptWindowsRecord, String> BODY = createField(DSL.name("body"), SQLDataType.CLOB, this, "");

    private JooqSearchTranscriptWindows(Name alias, Table<JooqSearchTranscriptWindowsRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.UUID)
        });
    }

    private JooqSearchTranscriptWindows(Name alias, Table<JooqSearchTranscriptWindowsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function());
    }

    /**
     * Create an aliased <code>public.search_transcript_windows</code> table
     * reference
     */
    public JooqSearchTranscriptWindows(String alias) {
        this(DSL.name(alias), SEARCH_TRANSCRIPT_WINDOWS);
    }

    /**
     * Create an aliased <code>public.search_transcript_windows</code> table
     * reference
     */
    public JooqSearchTranscriptWindows(Name alias) {
        this(alias, SEARCH_TRANSCRIPT_WINDOWS);
    }

    /**
     * Create a <code>public.search_transcript_windows</code> table reference
     */
    public JooqSearchTranscriptWindows() {
        this(DSL.name("search_transcript_windows"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public JooqSearchTranscriptWindows as(String alias) {
        return new JooqSearchTranscriptWindows(DSL.name(alias), this, parameters);
    }

    @Override
    public JooqSearchTranscriptWindows as(Name alias) {
        return new JooqSearchTranscriptWindows(alias, this, parameters);
    }

    @Override
    public JooqSearchTranscriptWindows as(Table<?> alias) {
        return new JooqSearchTranscriptWindows(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqSearchTranscriptWindows rename(String name) {
        return new JooqSearchTranscriptWindows(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqSearchTranscriptWindows rename(Name name) {
        return new JooqSearchTranscriptWindows(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqSearchTranscriptWindows rename(Table<?> name) {
        return new JooqSearchTranscriptWindows(name.getQualifiedName(), null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public JooqSearchTranscriptWindows call(
          UUID pTranscriptUuid
    ) {
        JooqSearchTranscriptWindows result = new JooqSearchTranscriptWindows(DSL.name("search_transcript_windows"), null, new Field[] {
            DSL.val(pTranscriptUuid, SQLDataType.UUID)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public JooqSearchTranscriptWindows call(
          Field<UUID> pTranscriptUuid
    ) {
        JooqSearchTranscriptWindows result = new JooqSearchTranscriptWindows(DSL.name("search_transcript_windows"), null, new Field[] {
            pTranscriptUuid
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
