/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.Indexes;
import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.tables.records.JooqShareCommentRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * A comment left through a share link by somebody with no Loom account. Kept
 * apart from `comment` so outside opinion never merges with the internal record
 * - which also matters before this text reaches the chat agent
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqShareComment extends TableImpl<JooqShareCommentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.share_comment</code>
     */
    public static final JooqShareComment SHARE_COMMENT = new JooqShareComment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqShareCommentRecord> getRecordType() {
        return JooqShareCommentRecord.class;
    }

    /**
     * The column <code>public.share_comment.uuid</code>.
     */
    public final TableField<JooqShareCommentRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuidv7()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.share_comment.share_uuid</code>.
     */
    public final TableField<JooqShareCommentRecord, java.util.UUID> SHARE_UUID = createField(DSL.name("share_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.share_comment.asset_uuid</code>. NULL means the
     * comment is about the shared collection as a whole rather than one member
     */
    public final TableField<JooqShareCommentRecord, java.util.UUID> ASSET_UUID = createField(DSL.name("asset_uuid"), SQLDataType.UUID, this, "NULL means the comment is about the shared collection as a whole rather than one member");

    /**
     * The column <code>public.share_comment.parent_uuid</code>. One level of
     * replies, matching what commentThread.ts renders
     */
    public final TableField<JooqShareCommentRecord, java.util.UUID> PARENT_UUID = createField(DSL.name("parent_uuid"), SQLDataType.UUID, this, "One level of replies, matching what commentThread.ts renders");

    /**
     * The column <code>public.share_comment.share_annotation_uuid</code>.
     */
    public final TableField<JooqShareCommentRecord, java.util.UUID> SHARE_ANNOTATION_UUID = createField(DSL.name("share_annotation_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.share_comment.text</code>.
     */
    public final TableField<JooqShareCommentRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.share_comment.author_name</code>.
     */
    public final TableField<JooqShareCommentRecord, String> AUTHOR_NAME = createField(DSL.name("author_name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.share_comment.created</code>.
     */
    public final TableField<JooqShareCommentRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.share_comment.edited</code>.
     */
    public final TableField<JooqShareCommentRecord, LocalDateTime> EDITED = createField(DSL.name("edited"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    private JooqShareComment(Name alias, Table<JooqShareCommentRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqShareComment(Name alias, Table<JooqShareCommentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("A comment left through a share link by somebody with no Loom account. Kept apart from `comment` so outside opinion never merges with the internal record - which also matters before this text reaches the chat agent"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.share_comment</code> table reference
     */
    public JooqShareComment(String alias) {
        this(DSL.name(alias), SHARE_COMMENT);
    }

    /**
     * Create an aliased <code>public.share_comment</code> table reference
     */
    public JooqShareComment(Name alias) {
        this(alias, SHARE_COMMENT);
    }

    /**
     * Create a <code>public.share_comment</code> table reference
     */
    public JooqShareComment() {
        this(DSL.name("share_comment"), null);
    }

    public <O extends Record> JooqShareComment(Table<O> child, ForeignKey<O, JooqShareCommentRecord> key) {
        super(child, key, SHARE_COMMENT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SHARE_COMMENT_ANNOTATION, Indexes.IDX_SHARE_COMMENT_ASSET, Indexes.IDX_SHARE_COMMENT_PARENT, Indexes.IDX_SHARE_COMMENT_SHARE);
    }

    @Override
    public UniqueKey<JooqShareCommentRecord> getPrimaryKey() {
        return Keys.SHARE_COMMENT_PKEY;
    }

    @Override
    public List<ForeignKey<JooqShareCommentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SHARE_COMMENT__SHARE_COMMENT_SHARE_FKEY, Keys.SHARE_COMMENT__SHARE_COMMENT_ASSET_FKEY, Keys.SHARE_COMMENT__SHARE_COMMENT_PARENT_FKEY, Keys.SHARE_COMMENT__SHARE_COMMENT_ANNOTATION_FKEY);
    }

    private transient JooqShare _share;
    private transient JooqAsset _asset;
    private transient JooqShareComment _shareComment;
    private transient JooqShareAnnotation _shareAnnotation;

    /**
     * Get the implicit join path to the <code>public.share</code> table.
     */
    public JooqShare share() {
        if (_share == null)
            _share = new JooqShare(this, Keys.SHARE_COMMENT__SHARE_COMMENT_SHARE_FKEY);

        return _share;
    }

    /**
     * Get the implicit join path to the <code>public.asset</code> table.
     */
    public JooqAsset asset() {
        if (_asset == null)
            _asset = new JooqAsset(this, Keys.SHARE_COMMENT__SHARE_COMMENT_ASSET_FKEY);

        return _asset;
    }

    /**
     * Get the implicit join path to the <code>public.share_comment</code>
     * table.
     */
    public JooqShareComment shareComment() {
        if (_shareComment == null)
            _shareComment = new JooqShareComment(this, Keys.SHARE_COMMENT__SHARE_COMMENT_PARENT_FKEY);

        return _shareComment;
    }

    /**
     * Get the implicit join path to the <code>public.share_annotation</code>
     * table.
     */
    public JooqShareAnnotation shareAnnotation() {
        if (_shareAnnotation == null)
            _shareAnnotation = new JooqShareAnnotation(this, Keys.SHARE_COMMENT__SHARE_COMMENT_ANNOTATION_FKEY);

        return _shareAnnotation;
    }

    @Override
    public JooqShareComment as(String alias) {
        return new JooqShareComment(DSL.name(alias), this);
    }

    @Override
    public JooqShareComment as(Name alias) {
        return new JooqShareComment(alias, this);
    }

    @Override
    public JooqShareComment as(Table<?> alias) {
        return new JooqShareComment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqShareComment rename(String name) {
        return new JooqShareComment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqShareComment rename(Name name) {
        return new JooqShareComment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqShareComment rename(Table<?> name) {
        return new JooqShareComment(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<java.util.UUID, java.util.UUID, java.util.UUID, java.util.UUID, java.util.UUID, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super java.util.UUID, ? super java.util.UUID, ? super java.util.UUID, ? super java.util.UUID, ? super java.util.UUID, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super java.util.UUID, ? super java.util.UUID, ? super java.util.UUID, ? super java.util.UUID, ? super java.util.UUID, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
