package io.metaloom.loom.rest.validation;

public interface LoomModelValidator extends
	AssetComponentModelValidator,
	AssetLocationModelValidator,
	AssetBinaryModelValidator,
	AssetPoolModelValidator,
	AttachmentModelValidator,
	AnnotationModelValidator,
	AssetModelValidator,
	BlacklistModelValidator,
	ChatModelValidator,
	NotificationModelValidator,
	SkillModelValidator,
	MemoryDenyRuleModelValidator,
	ChatSessionModelValidator,
	CollectionModelValidator,
	RemixModelValidator,
	ShareModelValidator,
	FailureReportModelValidator,
	ClusterModelValidator,
	CommentModelValidator,
	DetectionModelValidator,
	EmbeddingModelValidator,
	UserModelValidator,
	GroupModelValidator,
	RoleModelValidator,
	TagModelValidator,
	TaskModelValidator,
	TokenModelValidator,
	LibraryModelValidator,
	PersonModelValidator,
	PipelineModelValidator,
	SpaceModelValidator,
	ReactionModelValidator,
	NodeResultModelValidator,
	JsonCompModelValidator,
	FingerprintCompModelValidator,
	SegmentCompModelValidator,
	TranscriptModelValidator,
	LoginModelValidator {

}
