/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqProjectLibrary;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqProjectLibraryRecord extends UpdatableRecordImpl<JooqProjectLibraryRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.project_library.project_uuid</code>.
     */
    public void setProjectUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.project_library.project_uuid</code>.
     */
    public UUID getProjectUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.project_library.library_uuid</code>.
     */
    public void setLibraryUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.project_library.library_uuid</code>.
     */
    public UUID getLibraryUuid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqProjectLibrary.PROJECT_LIBRARY.PROJECT_UUID;
    }

    @Override
    public Field<UUID> field2() {
        return JooqProjectLibrary.PROJECT_LIBRARY.LIBRARY_UUID;
    }

    @Override
    public UUID component1() {
        return getProjectUuid();
    }

    @Override
    public UUID component2() {
        return getLibraryUuid();
    }

    @Override
    public UUID value1() {
        return getProjectUuid();
    }

    @Override
    public UUID value2() {
        return getLibraryUuid();
    }

    @Override
    public JooqProjectLibraryRecord value1(UUID value) {
        setProjectUuid(value);
        return this;
    }

    @Override
    public JooqProjectLibraryRecord value2(UUID value) {
        setLibraryUuid(value);
        return this;
    }

    @Override
    public JooqProjectLibraryRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqProjectLibraryRecord
     */
    public JooqProjectLibraryRecord() {
        super(JooqProjectLibrary.PROJECT_LIBRARY);
    }

    /**
     * Create a detached, initialised JooqProjectLibraryRecord
     */
    public JooqProjectLibraryRecord(UUID projectUuid, UUID libraryUuid) {
        super(JooqProjectLibrary.PROJECT_LIBRARY);

        setProjectUuid(projectUuid);
        setLibraryUuid(libraryUuid);
    }
}
