/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqAttachmentBinary;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqAttachmentBinaryRecord extends UpdatableRecordImpl<JooqAttachmentBinaryRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.attachment_binary.sha512sum</code>.
     */
    public void setSha512sum(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.attachment_binary.sha512sum</code>.
     */
    public String getSha512sum() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.attachment_binary.size</code>.
     */
    public void setSize(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.attachment_binary.size</code>.
     */
    public Long getSize() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JooqAttachmentBinary.ATTACHMENT_BINARY.SHA512SUM;
    }

    @Override
    public Field<Long> field2() {
        return JooqAttachmentBinary.ATTACHMENT_BINARY.SIZE;
    }

    @Override
    public String component1() {
        return getSha512sum();
    }

    @Override
    public Long component2() {
        return getSize();
    }

    @Override
    public String value1() {
        return getSha512sum();
    }

    @Override
    public Long value2() {
        return getSize();
    }

    @Override
    public JooqAttachmentBinaryRecord value1(String value) {
        setSha512sum(value);
        return this;
    }

    @Override
    public JooqAttachmentBinaryRecord value2(Long value) {
        setSize(value);
        return this;
    }

    @Override
    public JooqAttachmentBinaryRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqAttachmentBinaryRecord
     */
    public JooqAttachmentBinaryRecord() {
        super(JooqAttachmentBinary.ATTACHMENT_BINARY);
    }

    /**
     * Create a detached, initialised JooqAttachmentBinaryRecord
     */
    public JooqAttachmentBinaryRecord(String sha512sum, Long size) {
        super(JooqAttachmentBinary.ATTACHMENT_BINARY);

        setSha512sum(sha512sum);
        setSize(size);
    }
}
