/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqRoleGroup;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqRoleGroupRecord extends UpdatableRecordImpl<JooqRoleGroupRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.role_group.group_uuid</code>.
     */
    public void setGroupUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.role_group.group_uuid</code>.
     */
    public UUID getGroupUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.role_group.role_uuid</code>.
     */
    public void setRoleUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.role_group.role_uuid</code>.
     */
    public UUID getRoleUuid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqRoleGroup.ROLE_GROUP.GROUP_UUID;
    }

    @Override
    public Field<UUID> field2() {
        return JooqRoleGroup.ROLE_GROUP.ROLE_UUID;
    }

    @Override
    public UUID component1() {
        return getGroupUuid();
    }

    @Override
    public UUID component2() {
        return getRoleUuid();
    }

    @Override
    public UUID value1() {
        return getGroupUuid();
    }

    @Override
    public UUID value2() {
        return getRoleUuid();
    }

    @Override
    public JooqRoleGroupRecord value1(UUID value) {
        setGroupUuid(value);
        return this;
    }

    @Override
    public JooqRoleGroupRecord value2(UUID value) {
        setRoleUuid(value);
        return this;
    }

    @Override
    public JooqRoleGroupRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqRoleGroupRecord
     */
    public JooqRoleGroupRecord() {
        super(JooqRoleGroup.ROLE_GROUP);
    }

    /**
     * Create a detached, initialised JooqRoleGroupRecord
     */
    public JooqRoleGroupRecord(UUID groupUuid, UUID roleUuid) {
        super(JooqRoleGroup.ROLE_GROUP);

        setGroupUuid(groupUuid);
        setRoleUuid(roleUuid);
    }
}
