/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqNodeDescriptorInstance;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Which worker claims which node contract, and at which version
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqNodeDescriptorInstanceRecord extends UpdatableRecordImpl<JooqNodeDescriptorInstanceRecord> implements Record5<String, UUID, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.node_descriptor_instance.node_id</code>. The node
     * TYPE id. Deliberately not a foreign key to node_descriptor: a worker also
     * claims built-in node ids, whose contracts are never persisted
     */
    public void setNodeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.node_descriptor_instance.node_id</code>. The node
     * TYPE id. Deliberately not a foreign key to node_descriptor: a worker also
     * claims built-in node ids, whose contracts are never persisted
     */
    public String getNodeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.node_descriptor_instance.instance_uuid</code>.
     */
    public void setInstanceUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.node_descriptor_instance.instance_uuid</code>.
     */
    public UUID getInstanceUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.node_descriptor_instance.version</code>.
     */
    public void setVersion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.node_descriptor_instance.version</code>.
     */
    public String getVersion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.node_descriptor_instance.body_hash</code>.
     */
    public void setBodyHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.node_descriptor_instance.body_hash</code>.
     */
    public String getBodyHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.node_descriptor_instance.last_announced</code>.
     */
    public void setLastAnnounced(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.node_descriptor_instance.last_announced</code>.
     */
    public LocalDateTime getLastAnnounced() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, UUID, String, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, UUID, String, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JooqNodeDescriptorInstance.NODE_DESCRIPTOR_INSTANCE.NODE_ID;
    }

    @Override
    public Field<UUID> field2() {
        return JooqNodeDescriptorInstance.NODE_DESCRIPTOR_INSTANCE.INSTANCE_UUID;
    }

    @Override
    public Field<String> field3() {
        return JooqNodeDescriptorInstance.NODE_DESCRIPTOR_INSTANCE.VERSION;
    }

    @Override
    public Field<String> field4() {
        return JooqNodeDescriptorInstance.NODE_DESCRIPTOR_INSTANCE.BODY_HASH;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JooqNodeDescriptorInstance.NODE_DESCRIPTOR_INSTANCE.LAST_ANNOUNCED;
    }

    @Override
    public String component1() {
        return getNodeId();
    }

    @Override
    public UUID component2() {
        return getInstanceUuid();
    }

    @Override
    public String component3() {
        return getVersion();
    }

    @Override
    public String component4() {
        return getBodyHash();
    }

    @Override
    public LocalDateTime component5() {
        return getLastAnnounced();
    }

    @Override
    public String value1() {
        return getNodeId();
    }

    @Override
    public UUID value2() {
        return getInstanceUuid();
    }

    @Override
    public String value3() {
        return getVersion();
    }

    @Override
    public String value4() {
        return getBodyHash();
    }

    @Override
    public LocalDateTime value5() {
        return getLastAnnounced();
    }

    @Override
    public JooqNodeDescriptorInstanceRecord value1(String value) {
        setNodeId(value);
        return this;
    }

    @Override
    public JooqNodeDescriptorInstanceRecord value2(UUID value) {
        setInstanceUuid(value);
        return this;
    }

    @Override
    public JooqNodeDescriptorInstanceRecord value3(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public JooqNodeDescriptorInstanceRecord value4(String value) {
        setBodyHash(value);
        return this;
    }

    @Override
    public JooqNodeDescriptorInstanceRecord value5(LocalDateTime value) {
        setLastAnnounced(value);
        return this;
    }

    @Override
    public JooqNodeDescriptorInstanceRecord values(String value1, UUID value2, String value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqNodeDescriptorInstanceRecord
     */
    public JooqNodeDescriptorInstanceRecord() {
        super(JooqNodeDescriptorInstance.NODE_DESCRIPTOR_INSTANCE);
    }

    /**
     * Create a detached, initialised JooqNodeDescriptorInstanceRecord
     */
    public JooqNodeDescriptorInstanceRecord(String nodeId, UUID instanceUuid, String version, String bodyHash, LocalDateTime lastAnnounced) {
        super(JooqNodeDescriptorInstance.NODE_DESCRIPTOR_INSTANCE);

        setNodeId(nodeId);
        setInstanceUuid(instanceUuid);
        setVersion(version);
        setBodyHash(bodyHash);
        setLastAnnounced(lastAnnounced);
    }
}
