/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqPerson;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqPersonRecord extends UpdatableRecordImpl<JooqPersonRecord> implements Record10<UUID, String, String, String, JsonObject, UUID, LocalDateTime, UUID, LocalDateTime, UUID> {

    private static final long serialVersionUID = 1L;

    public void setUuid(UUID value) {
        set(0, value);
    }

    public UUID getUuid() {
        return (UUID) get(0);
    }

    public void setAlias(String value) {
        set(1, value);
    }

    public String getAlias() {
        return (String) get(1);
    }

    public void setFirstname(String value) {
        set(2, value);
    }

    public String getFirstname() {
        return (String) get(2);
    }

    public void setLastname(String value) {
        set(3, value);
    }

    public String getLastname() {
        return (String) get(3);
    }

    public void setMeta(JsonObject value) {
        set(4, value);
    }

    public JsonObject getMeta() {
        return (JsonObject) get(4);
    }

    public void setPrimaryImageUuid(UUID value) {
        set(5, value);
    }

    public UUID getPrimaryImageUuid() {
        return (UUID) get(5);
    }

    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    public void setCreatorUuid(UUID value) {
        set(7, value);
    }

    public UUID getCreatorUuid() {
        return (UUID) get(7);
    }

    public void setEdited(LocalDateTime value) {
        set(8, value);
    }

    public LocalDateTime getEdited() {
        return (LocalDateTime) get(8);
    }

    public void setEditorUuid(UUID value) {
        set(9, value);
    }

    public UUID getEditorUuid() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, String, String, String, JsonObject, UUID, LocalDateTime, UUID, LocalDateTime, UUID> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, String, String, String, JsonObject, UUID, LocalDateTime, UUID, LocalDateTime, UUID> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqPerson.PERSON.UUID;
    }

    @Override
    public Field<String> field2() {
        return JooqPerson.PERSON.ALIAS;
    }

    @Override
    public Field<String> field3() {
        return JooqPerson.PERSON.FIRSTNAME;
    }

    @Override
    public Field<String> field4() {
        return JooqPerson.PERSON.LASTNAME;
    }

    @Override
    public Field<JsonObject> field5() {
        return JooqPerson.PERSON.META;
    }

    @Override
    public Field<UUID> field6() {
        return JooqPerson.PERSON.PRIMARY_IMAGE_UUID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JooqPerson.PERSON.CREATED;
    }

    @Override
    public Field<UUID> field8() {
        return JooqPerson.PERSON.CREATOR_UUID;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return JooqPerson.PERSON.EDITED;
    }

    @Override
    public Field<UUID> field10() {
        return JooqPerson.PERSON.EDITOR_UUID;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getAlias();
    }

    @Override
    public String component3() {
        return getFirstname();
    }

    @Override
    public String component4() {
        return getLastname();
    }

    @Override
    public JsonObject component5() {
        return getMeta();
    }

    @Override
    public UUID component6() {
        return getPrimaryImageUuid();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public UUID component8() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime component9() {
        return getEdited();
    }

    @Override
    public UUID component10() {
        return getEditorUuid();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getAlias();
    }

    @Override
    public String value3() {
        return getFirstname();
    }

    @Override
    public String value4() {
        return getLastname();
    }

    @Override
    public JsonObject value5() {
        return getMeta();
    }

    @Override
    public UUID value6() {
        return getPrimaryImageUuid();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public UUID value8() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime value9() {
        return getEdited();
    }

    @Override
    public UUID value10() {
        return getEditorUuid();
    }

    @Override
    public JooqPersonRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public JooqPersonRecord value2(String value) {
        setAlias(value);
        return this;
    }

    @Override
    public JooqPersonRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public JooqPersonRecord value4(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public JooqPersonRecord value5(JsonObject value) {
        setMeta(value);
        return this;
    }

    @Override
    public JooqPersonRecord value6(UUID value) {
        setPrimaryImageUuid(value);
        return this;
    }

    @Override
    public JooqPersonRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JooqPersonRecord value8(UUID value) {
        setCreatorUuid(value);
        return this;
    }

    @Override
    public JooqPersonRecord value9(LocalDateTime value) {
        setEdited(value);
        return this;
    }

    @Override
    public JooqPersonRecord value10(UUID value) {
        setEditorUuid(value);
        return this;
    }

    @Override
    public JooqPersonRecord values(UUID value1, String value2, String value3, String value4, JsonObject value5, UUID value6, LocalDateTime value7, UUID value8, LocalDateTime value9, UUID value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public JooqPersonRecord() {
        super(JooqPerson.PERSON);
    }

    public JooqPersonRecord(UUID uuid, String alias, String firstname, String lastname, JsonObject meta, UUID primaryImageUuid, LocalDateTime created, UUID creatorUuid, LocalDateTime edited, UUID editorUuid) {
        super(JooqPerson.PERSON);

        setUuid(uuid);
        setAlias(alias);
        setFirstname(firstname);
        setLastname(lastname);
        setMeta(meta);
        setPrimaryImageUuid(primaryImageUuid);
        setCreated(created);
        setCreatorUuid(creatorUuid);
        setEdited(edited);
        setEditorUuid(editorUuid);
    }
}
