/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.enums.JooqReviewStatus;
import io.metaloom.loom.db.jooq.tables.JooqCluster;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * A group of embeddings that a producer believes belong to one subject,
 * carrying a human confirm/reject decision. type='face' clusters are proposed
 * per asset by the facedetect node and confirmed into a person.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqClusterRecord extends UpdatableRecordImpl<JooqClusterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.cluster.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.cluster.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.cluster.name</code>. Human-supplied label. NULL
     * for a machine proposal nobody has named yet. Unique per (type, name) when
     * set, so two cluster types may share a name.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.cluster.name</code>. Human-supplied label. NULL
     * for a machine proposal nobody has named yet. Unique per (type, name) when
     * set, so two cluster types may share a name.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.cluster.meta</code>. Custom meta properties to
     * the embedding.
     */
    public void setMeta(JsonObject value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.cluster.meta</code>. Custom meta properties to
     * the embedding.
     */
    public JsonObject getMeta() {
        return (JsonObject) get(2);
    }

    /**
     * Setter for <code>public.cluster.type</code>. Type of the cluster (e.g.
     * person)
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.cluster.type</code>. Type of the cluster (e.g.
     * person)
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.cluster.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.cluster.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.cluster.creator_uuid</code>. NULL when written by
     * a Cortex worker rather than a user (see cortex_instance)
     */
    public void setCreatorUuid(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.cluster.creator_uuid</code>. NULL when written by
     * a Cortex worker rather than a user (see cortex_instance)
     */
    public UUID getCreatorUuid() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.cluster.edited</code>.
     */
    public void setEdited(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.cluster.edited</code>.
     */
    public LocalDateTime getEdited() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.cluster.editor_uuid</code>. NULL when written by
     * a Cortex worker rather than a user (see cortex_instance)
     */
    public void setEditorUuid(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.cluster.editor_uuid</code>. NULL when written by
     * a Cortex worker rather than a user (see cortex_instance)
     */
    public UUID getEditorUuid() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.cluster.node_kind</code>. Producing node kind,
     * e.g. facedetect. NULL for a human-authored cluster.
     */
    public void setNodeKind(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.cluster.node_kind</code>. Producing node kind,
     * e.g. facedetect. NULL for a human-authored cluster.
     */
    public String getNodeKind() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.cluster.node_id</code>.
     */
    public void setNodeId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.cluster.node_id</code>.
     */
    public String getNodeId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.cluster.producer_version</code>. Version of the
     * producer and its model, so a model change can retire stale proposals via
     * WHERE node_kind = ? AND producer_version &lt;&gt; ?.
     */
    public void setProducerVersion(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.cluster.producer_version</code>. Version of the
     * producer and its model, so a model change can retire stale proposals via
     * WHERE node_kind = ? AND producer_version &lt;&gt; ?.
     */
    public String getProducerVersion() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.cluster.run_uuid</code>.
     */
    public void setRunUuid(UUID value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.cluster.run_uuid</code>.
     */
    public UUID getRunUuid() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>public.cluster.task_uuid</code>.
     */
    public void setTaskUuid(UUID value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.cluster.task_uuid</code>.
     */
    public UUID getTaskUuid() {
        return (UUID) get(12);
    }

    /**
     * Setter for <code>public.cluster.asset_uuid</code>. The asset this cluster
     * was computed within. NULL for a human-authored cluster or a phase-2
     * library-wide one.
     */
    public void setAssetUuid(UUID value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.cluster.asset_uuid</code>. The asset this cluster
     * was computed within. NULL for a human-authored cluster or a phase-2
     * library-wide one.
     */
    public UUID getAssetUuid() {
        return (UUID) get(13);
    }

    /**
     * Setter for <code>public.cluster.cluster_index</code>. Ordinal of this
     * cluster within (asset_uuid, node_kind), assigned deterministically by the
     * producer so a re-run upserts rather than appends.
     */
    public void setClusterIndex(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.cluster.cluster_index</code>. Ordinal of this
     * cluster within (asset_uuid, node_kind), assigned deterministically by the
     * producer so a re-run upserts rather than appends.
     */
    public Integer getClusterIndex() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.cluster.status</code>. PENDING (awaiting review),
     * CONFIRMED (linked to a person) or REJECTED (not a real subject).
     */
    public void setStatus(JooqReviewStatus value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.cluster.status</code>. PENDING (awaiting review),
     * CONFIRMED (linked to a person) or REJECTED (not a real subject).
     */
    public JooqReviewStatus getStatus() {
        return (JooqReviewStatus) get(15);
    }

    /**
     * Setter for <code>public.cluster.person_uuid</code>. The person a reviewer
     * confirmed this cluster to be. SET NULL on person delete: the review
     * record outlives the person row.
     */
    public void setPersonUuid(UUID value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.cluster.person_uuid</code>. The person a reviewer
     * confirmed this cluster to be. SET NULL on person delete: the review
     * record outlives the person row.
     */
    public UUID getPersonUuid() {
        return (UUID) get(16);
    }

    /**
     * Setter for <code>public.cluster.score</code>. Cohesion: mean cosine
     * similarity of the members to the centroid. NULL for a singleton, which
     * has nothing to cohere with.
     */
    public void setScore(Float value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.cluster.score</code>. Cohesion: mean cosine
     * similarity of the members to the centroid. NULL for a singleton, which
     * has nothing to cohere with.
     */
    public Float getScore() {
        return (Float) get(17);
    }

    /**
     * Setter for <code>public.cluster.centroid</code>. Unit-normalised mean of
     * the member vectors. Only comparable against embeddings sharing this row's
     * (type, model, dimensions).
     */
    public void setCentroid(Float[] value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.cluster.centroid</code>. Unit-normalised mean of
     * the member vectors. Only comparable against embeddings sharing this row's
     * (type, model, dimensions).
     */
    public Float[] getCentroid() {
        return (Float[]) get(18);
    }

    /**
     * Setter for <code>public.cluster.model</code>. Model the member embeddings
     * were produced by; qualifies "centroid".
     */
    public void setModel(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.cluster.model</code>. Model the member embeddings
     * were produced by; qualifies "centroid".
     */
    public String getModel() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.cluster.dimensions</code>. Length of "centroid";
     * qualifies it together with "model".
     */
    public void setDimensions(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.cluster.dimensions</code>. Length of "centroid";
     * qualifies it together with "model".
     */
    public Integer getDimensions() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>public.cluster.reviewed_at</code>. When a human decided.
     * NULL while PENDING. Distinct from "edited", which the producing node
     * touches on every re-run.
     */
    public void setReviewedAt(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.cluster.reviewed_at</code>. When a human decided.
     * NULL while PENDING. Distinct from "edited", which the producing node
     * touches on every re-run.
     */
    public LocalDateTime getReviewedAt() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>public.cluster.reviewer_uuid</code>. The user who
     * decided. Distinct from editor_uuid, which is machine-written provenance
     * (V2.47).
     */
    public void setReviewerUuid(UUID value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.cluster.reviewer_uuid</code>. The user who
     * decided. Distinct from editor_uuid, which is machine-written provenance
     * (V2.47).
     */
    public UUID getReviewerUuid() {
        return (UUID) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqClusterRecord
     */
    public JooqClusterRecord() {
        super(JooqCluster.CLUSTER);
    }

    /**
     * Create a detached, initialised JooqClusterRecord
     */
    public JooqClusterRecord(UUID uuid, String name, JsonObject meta, String type, LocalDateTime created, UUID creatorUuid, LocalDateTime edited, UUID editorUuid, String nodeKind, String nodeId, String producerVersion, UUID runUuid, UUID taskUuid, UUID assetUuid, Integer clusterIndex, JooqReviewStatus status, UUID personUuid, Float score, Float[] centroid, String model, Integer dimensions, LocalDateTime reviewedAt, UUID reviewerUuid) {
        super(JooqCluster.CLUSTER);

        setUuid(uuid);
        setName(name);
        setMeta(meta);
        setType(type);
        setCreated(created);
        setCreatorUuid(creatorUuid);
        setEdited(edited);
        setEditorUuid(editorUuid);
        setNodeKind(nodeKind);
        setNodeId(nodeId);
        setProducerVersion(producerVersion);
        setRunUuid(runUuid);
        setTaskUuid(taskUuid);
        setAssetUuid(assetUuid);
        setClusterIndex(clusterIndex);
        setStatus(status);
        setPersonUuid(personUuid);
        setScore(score);
        setCentroid(centroid);
        setModel(model);
        setDimensions(dimensions);
        setReviewedAt(reviewedAt);
        setReviewerUuid(reviewerUuid);
    }
}
