/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.api.pipeline.NodeTaskState;
import io.metaloom.loom.db.jooq.tables.JooqPipelineNodeTask;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * One node execution against one media item
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqPipelineNodeTaskRecord extends UpdatableRecordImpl<JooqPipelineNodeTaskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pipeline_node_task.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.pipeline_node_task.item_uuid</code>. The item
     * this node ran against
     */
    public void setItemUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.item_uuid</code>. The item
     * this node ran against
     */
    public UUID getItemUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.pipeline_node_task.run_uuid</code>. Denormalised
     * from the item so run-scoped queries need no join
     */
    public void setRunUuid(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.run_uuid</code>. Denormalised
     * from the item so run-scoped queries need no join
     */
    public UUID getRunUuid() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.pipeline_node_task.node_id</code>. Graph-local
     * node id, unique within the pipeline definition
     */
    public void setNodeId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.node_id</code>. Graph-local
     * node id, unique within the pipeline definition
     */
    public String getNodeId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.pipeline_node_task.node_kind</code>. Node kind,
     * used to route the task to a capable worker
     */
    public void setNodeKind(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.node_kind</code>. Node kind,
     * used to route the task to a capable worker
     */
    public String getNodeKind() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.pipeline_node_task.state</code>. PENDING,
     * RUNNING, COMPLETED, FAILED, SKIPPED or DEAD_LETTER
     */
    public void setState(NodeTaskState value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.state</code>. PENDING,
     * RUNNING, COMPLETED, FAILED, SKIPPED or DEAD_LETTER
     */
    public NodeTaskState getState() {
        return (NodeTaskState) get(5);
    }

    /**
     * Setter for <code>public.pipeline_node_task.attempt</code>. How many times
     * this task has been dispatched
     */
    public void setAttempt(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.attempt</code>. How many times
     * this task has been dispatched
     */
    public Integer getAttempt() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.pipeline_node_task.max_attempts</code>. Attempt
     * ceiling before the task is dead-lettered
     */
    public void setMaxAttempts(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.max_attempts</code>. Attempt
     * ceiling before the task is dead-lettered
     */
    public Integer getMaxAttempts() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.pipeline_node_task.leased_by</code>. Processor
     * node id currently holding the task
     */
    public void setLeasedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.leased_by</code>. Processor
     * node id currently holding the task
     */
    public String getLeasedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.pipeline_node_task.lease_expires_at</code>. When
     * the lease lapses and the task returns to PENDING
     */
    public void setLeaseExpiresAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.lease_expires_at</code>. When
     * the lease lapses and the task returns to PENDING
     */
    public LocalDateTime getLeaseExpiresAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.pipeline_node_task.started</code>.
     */
    public void setStarted(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.started</code>.
     */
    public LocalDateTime getStarted() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.pipeline_node_task.finished</code>.
     */
    public void setFinished(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.finished</code>.
     */
    public LocalDateTime getFinished() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.pipeline_node_task.duration_ms</code>.
     * Worker-reported execution time
     */
    public void setDurationMs(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.duration_ms</code>.
     * Worker-reported execution time
     */
    public Long getDurationMs() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.pipeline_node_task.error_message</code>. Failure
     * detail or skip reason
     */
    public void setErrorMessage(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.error_message</code>. Failure
     * detail or skip reason
     */
    public String getErrorMessage() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.pipeline_node_task.outputs</code>. Node outputs
     * keyed by output port id; each value is a PortPayload carrying the
     * declared content type, cardinality and origin-tagged elements
     */
    public void setOutputs(JsonObject value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.outputs</code>. Node outputs
     * keyed by output port id; each value is a PortPayload carrying the
     * declared content type, cardinality and origin-tagged elements
     */
    public JsonObject getOutputs() {
        return (JsonObject) get(14);
    }

    /**
     * Setter for <code>public.pipeline_node_task.meta</code>.
     */
    public void setMeta(JsonObject value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.meta</code>.
     */
    public JsonObject getMeta() {
        return (JsonObject) get(15);
    }

    /**
     * Setter for <code>public.pipeline_node_task.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>public.pipeline_node_task.creator_uuid</code>.
     */
    public void setCreatorUuid(UUID value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.creator_uuid</code>.
     */
    public UUID getCreatorUuid() {
        return (UUID) get(17);
    }

    /**
     * Setter for <code>public.pipeline_node_task.edited</code>.
     */
    public void setEdited(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.edited</code>.
     */
    public LocalDateTime getEdited() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>public.pipeline_node_task.editor_uuid</code>.
     */
    public void setEditorUuid(UUID value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.editor_uuid</code>.
     */
    public UUID getEditorUuid() {
        return (UUID) get(19);
    }

    /**
     * Setter for <code>public.pipeline_node_task.element_seq</code>. Which
     * element of a fanned-out sequence this execution covers; 0 when the node
     * runs once per item
     */
    public void setElementSeq(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.element_seq</code>. Which
     * element of a fanned-out sequence this execution covers; 0 when the node
     * runs once per item
     */
    public Integer getElementSeq() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>public.pipeline_node_task.previews</code>. Opt-in
     * per-run debugging previews keyed by output port id; each value is a
     * NodePreview {mimeType, width, height, data (base64), skippedReason}. NULL
     * when the run did not request previews. Run-scoped and pruned with the run
     * — never catalogue state.
     */
    public void setPreviews(JsonObject value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.previews</code>. Opt-in
     * per-run debugging previews keyed by output port id; each value is a
     * NodePreview {mimeType, width, height, data (base64), skippedReason}. NULL
     * when the run did not request previews. Run-scoped and pruned with the run
     * — never catalogue state.
     */
    public JsonObject getPreviews() {
        return (JsonObject) get(21);
    }

    /**
     * Setter for <code>public.pipeline_node_task.generation</code>. Which
     * attempt at this execution the row records; 0 for the only run of an
     * ordinary task, counting up per operator-requested re-execution of a node
     * held at a breakpoint
     */
    public void setGeneration(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.pipeline_node_task.generation</code>. Which
     * attempt at this execution the row records; 0 for the only run of an
     * ordinary task, counting up per operator-requested re-execution of a node
     * held at a breakpoint
     */
    public Integer getGeneration() {
        return (Integer) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqPipelineNodeTaskRecord
     */
    public JooqPipelineNodeTaskRecord() {
        super(JooqPipelineNodeTask.PIPELINE_NODE_TASK);
    }

    /**
     * Create a detached, initialised JooqPipelineNodeTaskRecord
     */
    public JooqPipelineNodeTaskRecord(UUID uuid, UUID itemUuid, UUID runUuid, String nodeId, String nodeKind, NodeTaskState state, Integer attempt, Integer maxAttempts, String leasedBy, LocalDateTime leaseExpiresAt, LocalDateTime started, LocalDateTime finished, Long durationMs, String errorMessage, JsonObject outputs, JsonObject meta, LocalDateTime created, UUID creatorUuid, LocalDateTime edited, UUID editorUuid, Integer elementSeq, JsonObject previews, Integer generation) {
        super(JooqPipelineNodeTask.PIPELINE_NODE_TASK);

        setUuid(uuid);
        setItemUuid(itemUuid);
        setRunUuid(runUuid);
        setNodeId(nodeId);
        setNodeKind(nodeKind);
        setState(state);
        setAttempt(attempt);
        setMaxAttempts(maxAttempts);
        setLeasedBy(leasedBy);
        setLeaseExpiresAt(leaseExpiresAt);
        setStarted(started);
        setFinished(finished);
        setDurationMs(durationMs);
        setErrorMessage(errorMessage);
        setOutputs(outputs);
        setMeta(meta);
        setCreated(created);
        setCreatorUuid(creatorUuid);
        setEdited(edited);
        setEditorUuid(editorUuid);
        setElementSeq(elementSeq);
        setPreviews(previews);
        setGeneration(generation);
    }
}
