/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqPerson;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqPersonRecord extends UpdatableRecordImpl<JooqPersonRecord> implements Record10<UUID, String, String, String, JsonObject, LocalDateTime, UUID, LocalDateTime, UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.person.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.person.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.person.alias</code>. Display alias for the person
     */
    public void setAlias(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.person.alias</code>. Display alias for the person
     */
    public String getAlias() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.person.firstname</code>. First name
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.person.firstname</code>. First name
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.person.lastname</code>. Last name
     */
    public void setLastname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.person.lastname</code>. Last name
     */
    public String getLastname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.person.meta</code>. Custom meta properties
     */
    public void setMeta(JsonObject value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.person.meta</code>. Custom meta properties
     */
    public JsonObject getMeta() {
        return (JsonObject) get(4);
    }

    /**
     * Setter for <code>public.person.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.person.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.person.creator_uuid</code>.
     */
    public void setCreatorUuid(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.person.creator_uuid</code>.
     */
    public UUID getCreatorUuid() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>public.person.edited</code>.
     */
    public void setEdited(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.person.edited</code>.
     */
    public LocalDateTime getEdited() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.person.editor_uuid</code>.
     */
    public void setEditorUuid(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.person.editor_uuid</code>.
     */
    public UUID getEditorUuid() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.person.avatar_attachment_uuid</code>. The person
     * image shown as this person's avatar. One of the person's own images,
     * never a pointer into an asset.
     */
    public void setAvatarAttachmentUuid(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.person.avatar_attachment_uuid</code>. The person
     * image shown as this person's avatar. One of the person's own images,
     * never a pointer into an asset.
     */
    public UUID getAvatarAttachmentUuid() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, String, String, String, JsonObject, LocalDateTime, UUID, LocalDateTime, UUID, UUID> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, String, String, String, JsonObject, LocalDateTime, UUID, LocalDateTime, UUID, UUID> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqPerson.PERSON.UUID;
    }

    @Override
    public Field<String> field2() {
        return JooqPerson.PERSON.ALIAS;
    }

    @Override
    public Field<String> field3() {
        return JooqPerson.PERSON.FIRSTNAME;
    }

    @Override
    public Field<String> field4() {
        return JooqPerson.PERSON.LASTNAME;
    }

    @Override
    public Field<JsonObject> field5() {
        return JooqPerson.PERSON.META;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return JooqPerson.PERSON.CREATED;
    }

    @Override
    public Field<UUID> field7() {
        return JooqPerson.PERSON.CREATOR_UUID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return JooqPerson.PERSON.EDITED;
    }

    @Override
    public Field<UUID> field9() {
        return JooqPerson.PERSON.EDITOR_UUID;
    }

    @Override
    public Field<UUID> field10() {
        return JooqPerson.PERSON.AVATAR_ATTACHMENT_UUID;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getAlias();
    }

    @Override
    public String component3() {
        return getFirstname();
    }

    @Override
    public String component4() {
        return getLastname();
    }

    @Override
    public JsonObject component5() {
        return getMeta();
    }

    @Override
    public LocalDateTime component6() {
        return getCreated();
    }

    @Override
    public UUID component7() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime component8() {
        return getEdited();
    }

    @Override
    public UUID component9() {
        return getEditorUuid();
    }

    @Override
    public UUID component10() {
        return getAvatarAttachmentUuid();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getAlias();
    }

    @Override
    public String value3() {
        return getFirstname();
    }

    @Override
    public String value4() {
        return getLastname();
    }

    @Override
    public JsonObject value5() {
        return getMeta();
    }

    @Override
    public LocalDateTime value6() {
        return getCreated();
    }

    @Override
    public UUID value7() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime value8() {
        return getEdited();
    }

    @Override
    public UUID value9() {
        return getEditorUuid();
    }

    @Override
    public UUID value10() {
        return getAvatarAttachmentUuid();
    }

    @Override
    public JooqPersonRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public JooqPersonRecord value2(String value) {
        setAlias(value);
        return this;
    }

    @Override
    public JooqPersonRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public JooqPersonRecord value4(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public JooqPersonRecord value5(JsonObject value) {
        setMeta(value);
        return this;
    }

    @Override
    public JooqPersonRecord value6(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JooqPersonRecord value7(UUID value) {
        setCreatorUuid(value);
        return this;
    }

    @Override
    public JooqPersonRecord value8(LocalDateTime value) {
        setEdited(value);
        return this;
    }

    @Override
    public JooqPersonRecord value9(UUID value) {
        setEditorUuid(value);
        return this;
    }

    @Override
    public JooqPersonRecord value10(UUID value) {
        setAvatarAttachmentUuid(value);
        return this;
    }

    @Override
    public JooqPersonRecord values(UUID value1, String value2, String value3, String value4, JsonObject value5, LocalDateTime value6, UUID value7, LocalDateTime value8, UUID value9, UUID value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqPersonRecord
     */
    public JooqPersonRecord() {
        super(JooqPerson.PERSON);
    }

    /**
     * Create a detached, initialised JooqPersonRecord
     */
    public JooqPersonRecord(UUID uuid, String alias, String firstname, String lastname, JsonObject meta, LocalDateTime created, UUID creatorUuid, LocalDateTime edited, UUID editorUuid, UUID avatarAttachmentUuid) {
        super(JooqPerson.PERSON);

        setUuid(uuid);
        setAlias(alias);
        setFirstname(firstname);
        setLastname(lastname);
        setMeta(meta);
        setCreated(created);
        setCreatorUuid(creatorUuid);
        setEdited(edited);
        setEditorUuid(editorUuid);
        setAvatarAttachmentUuid(avatarAttachmentUuid);
    }
}
