/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqMemoryDenyRule;
import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Instance-wide denylist of regular expressions which must never be stored in
 * the agent memory bank
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqMemoryDenyRuleRecord extends UpdatableRecordImpl<JooqMemoryDenyRuleRecord> implements Record10<UUID, String, String, String, Boolean, JsonObject, LocalDateTime, UUID, LocalDateTime, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.memory_deny_rule.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.memory_deny_rule.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.memory_deny_rule.name</code>. Human readable rule
     * name, unique across the instance
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.memory_deny_rule.name</code>. Human readable rule
     * name, unique across the instance
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.memory_deny_rule.pattern</code>. Java regular
     * expression matched against the note body and title; use alternation to
     * cover several phrases in one rule
     */
    public void setPattern(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.memory_deny_rule.pattern</code>. Java regular
     * expression matched against the note body and title; use alternation to
     * cover several phrases in one rule
     */
    public String getPattern() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.memory_deny_rule.message</code>. Message returned
     * to the agent when this rule rejects a write; it must explain the problem
     * without echoing the matched text
     */
    public void setMessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.memory_deny_rule.message</code>. Message returned
     * to the agent when this rule rejects a write; it must explain the problem
     * without echoing the matched text
     */
    public String getMessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.memory_deny_rule.enabled</code>. Disabled rules
     * are kept for reference but never matched
     */
    public void setEnabled(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.memory_deny_rule.enabled</code>. Disabled rules
     * are kept for reference but never matched
     */
    public Boolean getEnabled() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.memory_deny_rule.meta</code>.
     */
    public void setMeta(JsonObject value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.memory_deny_rule.meta</code>.
     */
    public JsonObject getMeta() {
        return (JsonObject) get(5);
    }

    /**
     * Setter for <code>public.memory_deny_rule.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.memory_deny_rule.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.memory_deny_rule.creator_uuid</code>.
     */
    public void setCreatorUuid(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.memory_deny_rule.creator_uuid</code>.
     */
    public UUID getCreatorUuid() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.memory_deny_rule.edited</code>.
     */
    public void setEdited(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.memory_deny_rule.edited</code>.
     */
    public LocalDateTime getEdited() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.memory_deny_rule.editor_uuid</code>.
     */
    public void setEditorUuid(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.memory_deny_rule.editor_uuid</code>.
     */
    public UUID getEditorUuid() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, String, String, String, Boolean, JsonObject, LocalDateTime, UUID, LocalDateTime, UUID> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, String, String, String, Boolean, JsonObject, LocalDateTime, UUID, LocalDateTime, UUID> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqMemoryDenyRule.MEMORY_DENY_RULE.UUID;
    }

    @Override
    public Field<String> field2() {
        return JooqMemoryDenyRule.MEMORY_DENY_RULE.NAME;
    }

    @Override
    public Field<String> field3() {
        return JooqMemoryDenyRule.MEMORY_DENY_RULE.PATTERN;
    }

    @Override
    public Field<String> field4() {
        return JooqMemoryDenyRule.MEMORY_DENY_RULE.MESSAGE;
    }

    @Override
    public Field<Boolean> field5() {
        return JooqMemoryDenyRule.MEMORY_DENY_RULE.ENABLED;
    }

    @Override
    public Field<JsonObject> field6() {
        return JooqMemoryDenyRule.MEMORY_DENY_RULE.META;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JooqMemoryDenyRule.MEMORY_DENY_RULE.CREATED;
    }

    @Override
    public Field<UUID> field8() {
        return JooqMemoryDenyRule.MEMORY_DENY_RULE.CREATOR_UUID;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return JooqMemoryDenyRule.MEMORY_DENY_RULE.EDITED;
    }

    @Override
    public Field<UUID> field10() {
        return JooqMemoryDenyRule.MEMORY_DENY_RULE.EDITOR_UUID;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getPattern();
    }

    @Override
    public String component4() {
        return getMessage();
    }

    @Override
    public Boolean component5() {
        return getEnabled();
    }

    @Override
    public JsonObject component6() {
        return getMeta();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public UUID component8() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime component9() {
        return getEdited();
    }

    @Override
    public UUID component10() {
        return getEditorUuid();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getPattern();
    }

    @Override
    public String value4() {
        return getMessage();
    }

    @Override
    public Boolean value5() {
        return getEnabled();
    }

    @Override
    public JsonObject value6() {
        return getMeta();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public UUID value8() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime value9() {
        return getEdited();
    }

    @Override
    public UUID value10() {
        return getEditorUuid();
    }

    @Override
    public JooqMemoryDenyRuleRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public JooqMemoryDenyRuleRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public JooqMemoryDenyRuleRecord value3(String value) {
        setPattern(value);
        return this;
    }

    @Override
    public JooqMemoryDenyRuleRecord value4(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public JooqMemoryDenyRuleRecord value5(Boolean value) {
        setEnabled(value);
        return this;
    }

    @Override
    public JooqMemoryDenyRuleRecord value6(JsonObject value) {
        setMeta(value);
        return this;
    }

    @Override
    public JooqMemoryDenyRuleRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JooqMemoryDenyRuleRecord value8(UUID value) {
        setCreatorUuid(value);
        return this;
    }

    @Override
    public JooqMemoryDenyRuleRecord value9(LocalDateTime value) {
        setEdited(value);
        return this;
    }

    @Override
    public JooqMemoryDenyRuleRecord value10(UUID value) {
        setEditorUuid(value);
        return this;
    }

    @Override
    public JooqMemoryDenyRuleRecord values(UUID value1, String value2, String value3, String value4, Boolean value5, JsonObject value6, LocalDateTime value7, UUID value8, LocalDateTime value9, UUID value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqMemoryDenyRuleRecord
     */
    public JooqMemoryDenyRuleRecord() {
        super(JooqMemoryDenyRule.MEMORY_DENY_RULE);
    }

    /**
     * Create a detached, initialised JooqMemoryDenyRuleRecord
     */
    public JooqMemoryDenyRuleRecord(UUID uuid, String name, String pattern, String message, Boolean enabled, JsonObject meta, LocalDateTime created, UUID creatorUuid, LocalDateTime edited, UUID editorUuid) {
        super(JooqMemoryDenyRule.MEMORY_DENY_RULE);

        setUuid(uuid);
        setName(name);
        setPattern(pattern);
        setMessage(message);
        setEnabled(enabled);
        setMeta(meta);
        setCreated(created);
        setCreatorUuid(creatorUuid);
        setEdited(edited);
        setEditorUuid(editorUuid);
    }
}
