/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.enums.JooqLoomPermission;
import io.metaloom.loom.db.jooq.tables.JooqUserPermission;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqUserPermissionRecord extends UpdatableRecordImpl<JooqUserPermissionRecord> implements Record3<UUID, String, JooqLoomPermission> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_permission.user_uuid</code>.
     */
    public void setUserUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_permission.user_uuid</code>.
     */
    public UUID getUserUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.user_permission.resource</code>.
     */
    public void setResource(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_permission.resource</code>.
     */
    public String getResource() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_permission.permission</code>. Permission
     * granted / granted to the resource
     */
    public void setPermission(JooqLoomPermission value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_permission.permission</code>. Permission
     * granted / granted to the resource
     */
    public JooqLoomPermission getPermission() {
        return (JooqLoomPermission) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, JooqLoomPermission> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, JooqLoomPermission> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqUserPermission.USER_PERMISSION.USER_UUID;
    }

    @Override
    public Field<String> field2() {
        return JooqUserPermission.USER_PERMISSION.RESOURCE;
    }

    @Override
    public Field<JooqLoomPermission> field3() {
        return JooqUserPermission.USER_PERMISSION.PERMISSION;
    }

    @Override
    public UUID component1() {
        return getUserUuid();
    }

    @Override
    public String component2() {
        return getResource();
    }

    @Override
    public JooqLoomPermission component3() {
        return getPermission();
    }

    @Override
    public UUID value1() {
        return getUserUuid();
    }

    @Override
    public String value2() {
        return getResource();
    }

    @Override
    public JooqLoomPermission value3() {
        return getPermission();
    }

    @Override
    public JooqUserPermissionRecord value1(UUID value) {
        setUserUuid(value);
        return this;
    }

    @Override
    public JooqUserPermissionRecord value2(String value) {
        setResource(value);
        return this;
    }

    @Override
    public JooqUserPermissionRecord value3(JooqLoomPermission value) {
        setPermission(value);
        return this;
    }

    @Override
    public JooqUserPermissionRecord values(UUID value1, String value2, JooqLoomPermission value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqUserPermissionRecord
     */
    public JooqUserPermissionRecord() {
        super(JooqUserPermission.USER_PERMISSION);
    }

    /**
     * Create a detached, initialised JooqUserPermissionRecord
     */
    public JooqUserPermissionRecord(UUID userUuid, String resource, JooqLoomPermission permission) {
        super(JooqUserPermission.USER_PERMISSION);

        setUserUuid(userUuid);
        setResource(resource);
        setPermission(permission);
    }
}
