/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqTagAsset;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Store tag &lt;-&gt; asset reference
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTagAssetRecord extends UpdatableRecordImpl<JooqTagAssetRecord> implements Record8<UUID, UUID, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tag_asset.tag_uuid</code>.
     */
    public void setTagUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tag_asset.tag_uuid</code>.
     */
    public UUID getTagUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.tag_asset.asset_uuid</code>.
     */
    public void setAssetUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tag_asset.asset_uuid</code>.
     */
    public UUID getAssetUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.tag_asset.time_from</code>.
     */
    public void setTimeFrom(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tag_asset.time_from</code>.
     */
    public Integer getTimeFrom() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.tag_asset.time_to</code>.
     */
    public void setTimeTo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tag_asset.time_to</code>.
     */
    public Integer getTimeTo() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.tag_asset.areaStartX</code>.
     */
    public void setAreastartx(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tag_asset.areaStartX</code>.
     */
    public Integer getAreastartx() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.tag_asset.areaStartY</code>.
     */
    public void setAreastarty(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tag_asset.areaStartY</code>.
     */
    public Integer getAreastarty() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tag_asset.areaWidth</code>.
     */
    public void setAreawidth(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tag_asset.areaWidth</code>.
     */
    public Integer getAreawidth() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.tag_asset.areaHeight</code>.
     */
    public void setAreaheight(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tag_asset.areaHeight</code>.
     */
    public Integer getAreaheight() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, UUID, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, UUID, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqTagAsset.TAG_ASSET.TAG_UUID;
    }

    @Override
    public Field<UUID> field2() {
        return JooqTagAsset.TAG_ASSET.ASSET_UUID;
    }

    @Override
    public Field<Integer> field3() {
        return JooqTagAsset.TAG_ASSET.TIME_FROM;
    }

    @Override
    public Field<Integer> field4() {
        return JooqTagAsset.TAG_ASSET.TIME_TO;
    }

    @Override
    public Field<Integer> field5() {
        return JooqTagAsset.TAG_ASSET.AREASTARTX;
    }

    @Override
    public Field<Integer> field6() {
        return JooqTagAsset.TAG_ASSET.AREASTARTY;
    }

    @Override
    public Field<Integer> field7() {
        return JooqTagAsset.TAG_ASSET.AREAWIDTH;
    }

    @Override
    public Field<Integer> field8() {
        return JooqTagAsset.TAG_ASSET.AREAHEIGHT;
    }

    @Override
    public UUID component1() {
        return getTagUuid();
    }

    @Override
    public UUID component2() {
        return getAssetUuid();
    }

    @Override
    public Integer component3() {
        return getTimeFrom();
    }

    @Override
    public Integer component4() {
        return getTimeTo();
    }

    @Override
    public Integer component5() {
        return getAreastartx();
    }

    @Override
    public Integer component6() {
        return getAreastarty();
    }

    @Override
    public Integer component7() {
        return getAreawidth();
    }

    @Override
    public Integer component8() {
        return getAreaheight();
    }

    @Override
    public UUID value1() {
        return getTagUuid();
    }

    @Override
    public UUID value2() {
        return getAssetUuid();
    }

    @Override
    public Integer value3() {
        return getTimeFrom();
    }

    @Override
    public Integer value4() {
        return getTimeTo();
    }

    @Override
    public Integer value5() {
        return getAreastartx();
    }

    @Override
    public Integer value6() {
        return getAreastarty();
    }

    @Override
    public Integer value7() {
        return getAreawidth();
    }

    @Override
    public Integer value8() {
        return getAreaheight();
    }

    @Override
    public JooqTagAssetRecord value1(UUID value) {
        setTagUuid(value);
        return this;
    }

    @Override
    public JooqTagAssetRecord value2(UUID value) {
        setAssetUuid(value);
        return this;
    }

    @Override
    public JooqTagAssetRecord value3(Integer value) {
        setTimeFrom(value);
        return this;
    }

    @Override
    public JooqTagAssetRecord value4(Integer value) {
        setTimeTo(value);
        return this;
    }

    @Override
    public JooqTagAssetRecord value5(Integer value) {
        setAreastartx(value);
        return this;
    }

    @Override
    public JooqTagAssetRecord value6(Integer value) {
        setAreastarty(value);
        return this;
    }

    @Override
    public JooqTagAssetRecord value7(Integer value) {
        setAreawidth(value);
        return this;
    }

    @Override
    public JooqTagAssetRecord value8(Integer value) {
        setAreaheight(value);
        return this;
    }

    @Override
    public JooqTagAssetRecord values(UUID value1, UUID value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqTagAssetRecord
     */
    public JooqTagAssetRecord() {
        super(JooqTagAsset.TAG_ASSET);
    }

    /**
     * Create a detached, initialised JooqTagAssetRecord
     */
    public JooqTagAssetRecord(UUID tagUuid, UUID assetUuid, Integer timeFrom, Integer timeTo, Integer areastartx, Integer areastarty, Integer areawidth, Integer areaheight) {
        super(JooqTagAsset.TAG_ASSET);

        setTagUuid(tagUuid);
        setAssetUuid(assetUuid);
        setTimeFrom(timeFrom);
        setTimeTo(timeTo);
        setAreastartx(areastartx);
        setAreastarty(areastarty);
        setAreawidth(areawidth);
        setAreaheight(areaheight);
    }
}
