/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqCollectionCluster;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqCollectionClusterRecord extends UpdatableRecordImpl<JooqCollectionClusterRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.collection_cluster.collection_uuid</code>.
     */
    public void setCollectionUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.collection_cluster.collection_uuid</code>.
     */
    public UUID getCollectionUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.collection_cluster.cluster_uuid</code>.
     */
    public void setClusterUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.collection_cluster.cluster_uuid</code>.
     */
    public UUID getClusterUuid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqCollectionCluster.COLLECTION_CLUSTER.COLLECTION_UUID;
    }

    @Override
    public Field<UUID> field2() {
        return JooqCollectionCluster.COLLECTION_CLUSTER.CLUSTER_UUID;
    }

    @Override
    public UUID component1() {
        return getCollectionUuid();
    }

    @Override
    public UUID component2() {
        return getClusterUuid();
    }

    @Override
    public UUID value1() {
        return getCollectionUuid();
    }

    @Override
    public UUID value2() {
        return getClusterUuid();
    }

    @Override
    public JooqCollectionClusterRecord value1(UUID value) {
        setCollectionUuid(value);
        return this;
    }

    @Override
    public JooqCollectionClusterRecord value2(UUID value) {
        setClusterUuid(value);
        return this;
    }

    @Override
    public JooqCollectionClusterRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqCollectionClusterRecord
     */
    public JooqCollectionClusterRecord() {
        super(JooqCollectionCluster.COLLECTION_CLUSTER);
    }

    /**
     * Create a detached, initialised JooqCollectionClusterRecord
     */
    public JooqCollectionClusterRecord(UUID collectionUuid, UUID clusterUuid) {
        super(JooqCollectionCluster.COLLECTION_CLUSTER);

        setCollectionUuid(collectionUuid);
        setClusterUuid(clusterUuid);
    }
}
