/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqAssetGeoComp;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Stores geo location information extracted from an asset
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqAssetGeoCompRecord extends UpdatableRecordImpl<JooqAssetGeoCompRecord> implements Record10<UUID, UUID, String, BigDecimal, BigDecimal, String, LocalDateTime, UUID, LocalDateTime, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.asset_geo_comp.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.asset_geo_comp.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.asset_geo_comp.asset_uuid</code>.
     */
    public void setAssetUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.asset_geo_comp.asset_uuid</code>.
     */
    public UUID getAssetUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.asset_geo_comp.source</code>. Name of the source
     * for the geo info - e.g. exif data
     */
    public void setSource(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.asset_geo_comp.source</code>. Name of the source
     * for the geo info - e.g. exif data
     */
    public String getSource() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.asset_geo_comp.geo_lon</code>.
     */
    public void setGeoLon(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.asset_geo_comp.geo_lon</code>.
     */
    public BigDecimal getGeoLon() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.asset_geo_comp.geo_lat</code>.
     */
    public void setGeoLat(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.asset_geo_comp.geo_lat</code>.
     */
    public BigDecimal getGeoLat() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.asset_geo_comp.geo_alias</code>.
     */
    public void setGeoAlias(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.asset_geo_comp.geo_alias</code>.
     */
    public String getGeoAlias() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.asset_geo_comp.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.asset_geo_comp.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.asset_geo_comp.creator_uuid</code>.
     */
    public void setCreatorUuid(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.asset_geo_comp.creator_uuid</code>.
     */
    public UUID getCreatorUuid() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.asset_geo_comp.edited</code>.
     */
    public void setEdited(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.asset_geo_comp.edited</code>.
     */
    public LocalDateTime getEdited() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.asset_geo_comp.editor_uuid</code>.
     */
    public void setEditorUuid(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.asset_geo_comp.editor_uuid</code>.
     */
    public UUID getEditorUuid() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, UUID, String, BigDecimal, BigDecimal, String, LocalDateTime, UUID, LocalDateTime, UUID> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, UUID, String, BigDecimal, BigDecimal, String, LocalDateTime, UUID, LocalDateTime, UUID> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqAssetGeoComp.ASSET_GEO_COMP.UUID;
    }

    @Override
    public Field<UUID> field2() {
        return JooqAssetGeoComp.ASSET_GEO_COMP.ASSET_UUID;
    }

    @Override
    public Field<String> field3() {
        return JooqAssetGeoComp.ASSET_GEO_COMP.SOURCE;
    }

    @Override
    public Field<BigDecimal> field4() {
        return JooqAssetGeoComp.ASSET_GEO_COMP.GEO_LON;
    }

    @Override
    public Field<BigDecimal> field5() {
        return JooqAssetGeoComp.ASSET_GEO_COMP.GEO_LAT;
    }

    @Override
    public Field<String> field6() {
        return JooqAssetGeoComp.ASSET_GEO_COMP.GEO_ALIAS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JooqAssetGeoComp.ASSET_GEO_COMP.CREATED;
    }

    @Override
    public Field<UUID> field8() {
        return JooqAssetGeoComp.ASSET_GEO_COMP.CREATOR_UUID;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return JooqAssetGeoComp.ASSET_GEO_COMP.EDITED;
    }

    @Override
    public Field<UUID> field10() {
        return JooqAssetGeoComp.ASSET_GEO_COMP.EDITOR_UUID;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public UUID component2() {
        return getAssetUuid();
    }

    @Override
    public String component3() {
        return getSource();
    }

    @Override
    public BigDecimal component4() {
        return getGeoLon();
    }

    @Override
    public BigDecimal component5() {
        return getGeoLat();
    }

    @Override
    public String component6() {
        return getGeoAlias();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public UUID component8() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime component9() {
        return getEdited();
    }

    @Override
    public UUID component10() {
        return getEditorUuid();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public UUID value2() {
        return getAssetUuid();
    }

    @Override
    public String value3() {
        return getSource();
    }

    @Override
    public BigDecimal value4() {
        return getGeoLon();
    }

    @Override
    public BigDecimal value5() {
        return getGeoLat();
    }

    @Override
    public String value6() {
        return getGeoAlias();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public UUID value8() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime value9() {
        return getEdited();
    }

    @Override
    public UUID value10() {
        return getEditorUuid();
    }

    @Override
    public JooqAssetGeoCompRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public JooqAssetGeoCompRecord value2(UUID value) {
        setAssetUuid(value);
        return this;
    }

    @Override
    public JooqAssetGeoCompRecord value3(String value) {
        setSource(value);
        return this;
    }

    @Override
    public JooqAssetGeoCompRecord value4(BigDecimal value) {
        setGeoLon(value);
        return this;
    }

    @Override
    public JooqAssetGeoCompRecord value5(BigDecimal value) {
        setGeoLat(value);
        return this;
    }

    @Override
    public JooqAssetGeoCompRecord value6(String value) {
        setGeoAlias(value);
        return this;
    }

    @Override
    public JooqAssetGeoCompRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JooqAssetGeoCompRecord value8(UUID value) {
        setCreatorUuid(value);
        return this;
    }

    @Override
    public JooqAssetGeoCompRecord value9(LocalDateTime value) {
        setEdited(value);
        return this;
    }

    @Override
    public JooqAssetGeoCompRecord value10(UUID value) {
        setEditorUuid(value);
        return this;
    }

    @Override
    public JooqAssetGeoCompRecord values(UUID value1, UUID value2, String value3, BigDecimal value4, BigDecimal value5, String value6, LocalDateTime value7, UUID value8, LocalDateTime value9, UUID value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqAssetGeoCompRecord
     */
    public JooqAssetGeoCompRecord() {
        super(JooqAssetGeoComp.ASSET_GEO_COMP);
    }

    /**
     * Create a detached, initialised JooqAssetGeoCompRecord
     */
    public JooqAssetGeoCompRecord(UUID uuid, UUID assetUuid, String source, BigDecimal geoLon, BigDecimal geoLat, String geoAlias, LocalDateTime created, UUID creatorUuid, LocalDateTime edited, UUID editorUuid) {
        super(JooqAssetGeoComp.ASSET_GEO_COMP);

        setUuid(uuid);
        setAssetUuid(assetUuid);
        setSource(source);
        setGeoLon(geoLon);
        setGeoLat(geoLat);
        setGeoAlias(geoAlias);
        setCreated(created);
        setCreatorUuid(creatorUuid);
        setEdited(edited);
        setEditorUuid(editorUuid);
    }
}
