/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqTagCluster;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Store tag &lt;-&gt; cluster reference
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTagClusterRecord extends UpdatableRecordImpl<JooqTagClusterRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tag_cluster.tag_uuid</code>.
     */
    public void setTagUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tag_cluster.tag_uuid</code>.
     */
    public UUID getTagUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.tag_cluster.cluster_uuid</code>.
     */
    public void setClusterUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tag_cluster.cluster_uuid</code>.
     */
    public UUID getClusterUuid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqTagCluster.TAG_CLUSTER.TAG_UUID;
    }

    @Override
    public Field<UUID> field2() {
        return JooqTagCluster.TAG_CLUSTER.CLUSTER_UUID;
    }

    @Override
    public UUID component1() {
        return getTagUuid();
    }

    @Override
    public UUID component2() {
        return getClusterUuid();
    }

    @Override
    public UUID value1() {
        return getTagUuid();
    }

    @Override
    public UUID value2() {
        return getClusterUuid();
    }

    @Override
    public JooqTagClusterRecord value1(UUID value) {
        setTagUuid(value);
        return this;
    }

    @Override
    public JooqTagClusterRecord value2(UUID value) {
        setClusterUuid(value);
        return this;
    }

    @Override
    public JooqTagClusterRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqTagClusterRecord
     */
    public JooqTagClusterRecord() {
        super(JooqTagCluster.TAG_CLUSTER);
    }

    /**
     * Create a detached, initialised JooqTagClusterRecord
     */
    public JooqTagClusterRecord(UUID tagUuid, UUID clusterUuid) {
        super(JooqTagCluster.TAG_CLUSTER);

        setTagUuid(tagUuid);
        setClusterUuid(clusterUuid);
    }
}
