/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqLibraryAsset;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqLibraryAssetRecord extends UpdatableRecordImpl<JooqLibraryAssetRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.library_asset.library_uuid</code>.
     */
    public void setLibraryUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.library_asset.library_uuid</code>.
     */
    public UUID getLibraryUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.library_asset.asset_uuid</code>.
     */
    public void setAssetUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.library_asset.asset_uuid</code>.
     */
    public UUID getAssetUuid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqLibraryAsset.LIBRARY_ASSET.LIBRARY_UUID;
    }

    @Override
    public Field<UUID> field2() {
        return JooqLibraryAsset.LIBRARY_ASSET.ASSET_UUID;
    }

    @Override
    public UUID component1() {
        return getLibraryUuid();
    }

    @Override
    public UUID component2() {
        return getAssetUuid();
    }

    @Override
    public UUID value1() {
        return getLibraryUuid();
    }

    @Override
    public UUID value2() {
        return getAssetUuid();
    }

    @Override
    public JooqLibraryAssetRecord value1(UUID value) {
        setLibraryUuid(value);
        return this;
    }

    @Override
    public JooqLibraryAssetRecord value2(UUID value) {
        setAssetUuid(value);
        return this;
    }

    @Override
    public JooqLibraryAssetRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqLibraryAssetRecord
     */
    public JooqLibraryAssetRecord() {
        super(JooqLibraryAsset.LIBRARY_ASSET);
    }

    /**
     * Create a detached, initialised JooqLibraryAssetRecord
     */
    public JooqLibraryAssetRecord(UUID libraryUuid, UUID assetUuid) {
        super(JooqLibraryAsset.LIBRARY_ASSET);

        setLibraryUuid(libraryUuid);
        setAssetUuid(assetUuid);
    }
}
