<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>io.metaloom.loom.service</groupId>
		<artifactId>loom-services</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>loom-service-graphql</artifactId>
	<name>Loom - Service :: GraphQL</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<!-- GraphQL -->
		<dependency>
			<groupId>com.graphql-java</groupId>
			<artifactId>graphql-java</artifactId>
			<version>25.0</version>
		</dependency>

		<!-- Loom internal -->
		<dependency>
			<groupId>io.metaloom.loom.db</groupId>
			<artifactId>loom-db-api</artifactId>
		</dependency>

		<!-- Test -->
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>4.11.0</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

</project>
