-- Add missing permission enum values for Asset Binary and Asset Pool management

ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'CREATE_ASSET_BINARY';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'READ_ASSET_BINARY';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'DELETE_ASSET_BINARY';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'UPDATE_ASSET_BINARY';

ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'CREATE_ASSET_POOL';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'READ_ASSET_POOL';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'DELETE_ASSET_POOL';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'UPDATE_ASSET_POOL';
