-- Add missing blacklist permissions
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'CREATE_BLACKLIST';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'READ_BLACKLIST';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'DELETE_BLACKLIST';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'UPDATE_BLACKLIST';

-- Add person permissions
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'CREATE_PERSON';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'READ_PERSON';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'DELETE_PERSON';
ALTER TYPE "loom_permission" ADD VALUE IF NOT EXISTS 'UPDATE_PERSON';
