package io.metaloom.loom.nodes.spec;

import static io.metaloom.loom.nodes.spec.ContentTypeRegistry.MEDIA_ANY;
import static io.metaloom.loom.nodes.spec.NodeCategory.SOURCE;
import static io.metaloom.loom.nodes.spec.NodeMode.SEQUENTIAL;
import static io.metaloom.loom.nodes.spec.ParameterType.BOOLEAN;
import static io.metaloom.loom.nodes.spec.PortSpec.one;

import java.util.List;

/**
 * Contracts that have no node class to derive them from.
 *
 * <p>
 * Every other built-in contract is now generated by harvesting the annotations on its node class —
 * see {@link GeneratedNodeDescriptorProvider}. {@code loom-fetch} cannot be: <strong>no such node
 * exists</strong>. It is a descriptor with nothing behind it, and has been for as long as the registry
 * has had a reconciliation table calling it out as an orphan.
 * </p>
 *
 * <p>
 * It is kept rather than quietly dropped because a saved pipeline that names it would otherwise stop
 * parsing, which is the one failure mode this whole design exists to avoid. Serving it means the graph
 * still opens and still saves; running it already fails at dispatch, where the error names the missing
 * worker.
 * </p>
 *
 * <p>
 * 🔴 This class is a holding pen, not a pattern. Adding a contract here means adding a node to the
 * palette that nothing can execute. The fix for {@code loom-fetch} is to decide whether the node
 * should exist — in which case write it and annotate it, and this class goes away entirely — or
 * whether the contract should be retired, in which case that needs a migration for any pipeline
 * already using it.
 * </p>
 */
public class OrphanNodeDescriptorProvider implements NodeDescriptorProvider {

	private static final List<String> STANDARD_EVENTS = List.of(
		"NODE_STARTED", "NODE_COMPLETED", "NODE_FAILED", "NODE_SKIPPED", "NODE_STATS");

	@Override
	public List<NodeDescriptor> getDescriptors() {
		return List.of(
			new NodeDescriptor()
				.setNodeId("loom-fetch")
				.setName("Loom Fetch")
				.setDescription("Fetches media references from the Loom backend.")
				.setIcon("cloud_download")
				.setCategory(SOURCE)
				.setInputPorts(List.of())
				.setOutputPorts(List.of(
					one("media", MEDIA_ANY)
						.describedAs("Media", "Every media reference the Loom backend handed out for processing")))
				.setParameters(List.of(
					new NodeParameter().setKey("enabled").setType(BOOLEAN).setDefaultValue(true)
						.setLabel("Enabled").setDescription("Whether this node is active in the pipeline")))
				.setDefaultConcurrency(1)
				.setDefaultMode(SEQUENTIAL)
				.setEvents(STANDARD_EVENTS));
	}
}
