package io.metaloom.loom.nodes.spec;

import static io.metaloom.loom.nodes.spec.ContentTypeRegistry.MEDIA_ANY;
import static io.metaloom.loom.nodes.spec.NodeCategory.SOURCE;
import static io.metaloom.loom.nodes.spec.NodeMode.SEQUENTIAL;
import static io.metaloom.loom.nodes.spec.ParameterType.BOOLEAN;
import static io.metaloom.loom.nodes.spec.PortSpec.one;

import java.util.List;

/**
 * Contracts that have no node class to derive them from.
 *
 * <p>
 * Every other built-in contract is generated by harvesting the annotations on its node class — see
 * {@link GeneratedNodeDescriptorProvider}. {@code loom-fetch} cannot be, and no longer needs to be:
 * <strong>it is executed by Loom, not by a worker</strong>. It is the source of every ad-hoc node run
 * ({@code POST /api/v1/node-runs}), and Loom already knows the media it would enumerate, so
 * {@code PipelineRunEngine.onItemDiscovered} synthesises its {@code media} output directly rather than
 * sending a {@code SOURCE_TASK} to anybody.
 * </p>
 *
 * <p>
 * A {@code loom-fetch} node therefore never reaches a dispatcher. If one ever does, that is a bug in
 * the graph builder — not a missing worker, and not something to fix by writing a cortex node. See
 * {@code spec/chat/AGENTIC_NODE_EXECUTION.md}.
 * </p>
 *
 * <p>
 * 🔴 This class is still not a pattern. Adding any <em>other</em> contract here means adding a node to
 * the palette that nothing can execute. A new entry needs either a node class to harvest or, as here,
 * an explicit Loom-side executor and a spec that says so.
 * </p>
 */
public class OrphanNodeDescriptorProvider implements NodeDescriptorProvider {

	private static final List<String> STANDARD_EVENTS = List.of(
		"NODE_STARTED", "NODE_COMPLETED", "NODE_FAILED", "NODE_SKIPPED", "NODE_STATS");

	@Override
	public List<NodeDescriptor> getDescriptors() {
		return List.of(
			new NodeDescriptor()
				.setNodeId("loom-fetch")
				.setName("Loom Fetch")
				.setDescription("Fetches media references from the Loom backend.")
				.setIcon("cloud_download")
				.setCategory(SOURCE)
				.setInputPorts(List.of())
				.setOutputPorts(List.of(
					one("media", MEDIA_ANY)
						.describedAs("Media", "Every media reference the Loom backend handed out for processing")))
				.setParameters(List.of(
					new NodeParameter().setKey("enabled").setType(BOOLEAN).setDefaultValue(true)
						.setLabel("Enabled").setDescription("Whether this node is active in the pipeline")))
				.setDefaultConcurrency(1)
				.setDefaultMode(SEQUENTIAL)
				.setEvents(STANDARD_EVENTS));
	}
}
