package io.metaloom.loom.client.common.method;

public interface ClientMethods extends
	UserMethods,
	AssetMethods,
	AssetLocationMethods,
	AssetBinaryMethods,
	AssetComponentMethods,
	AssetPoolMethods,
	AttachmentMethods,
	BlacklistMethods,
	ChatMethods,
	SkillMethods,
	ClusterMethods,
	DetectionMethods,
	GroupMethods,
	RoleMethods,
	CollectionMethods,
	RemixMethods,
	ShareMethods,
	AnnotationMethods,
	TaskMethods,
	NotificationMethods,
	TagMethods,
	AuthenticationMethods,
	ReactionMethods,
	TokenMethods,
	LibraryMethods,
	PersonMethods,
	PipelineMethods,
	SpaceMethods,
	CommentMethods,
	EmbeddingMethods,
	TranscriptMethods,
	NodeResultMethods,
	NodeRunMethods,
	JsonCompMethods,
	FingerprintCompMethods,
	SegmentCompMethods,
	SearchMethods,
	SimilarityMethods,
	SearchIndexMethods,
	DedupGroupMethods,
	GraphQLMethods,
	HealthMethods,
	MetricsMethods,
	DbIntegrityMethods,
	StorageMethods,
	InfoMethods {

}
