---
title: Maven Artifacts
---

All Loom artifacts are published under the `io.metaloom` group.

== BOM POM

Use the BOM to align versions across Loom and Cortex modules:

[source,xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.metaloom</groupId>
      <artifactId>bom</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
----

== REST Client

[source,xml]
----
<dependency>
    <groupId>io.metaloom.loom.client</groupId>
    <artifactId>loom-rest-client</artifactId>
    <version>1.0.0-SNAPSHOT</version>
</dependency>
----

== gRPC Client

[source,xml]
----
<dependency>
    <groupId>io.metaloom.loom.client</groupId>
    <artifactId>loom-grpc-client</artifactId>
    <version>1.0.0-SNAPSHOT</version>
</dependency>
----

== REST Model

[source,xml]
----
<dependency>
    <groupId>io.metaloom.loom</groupId>
    <artifactId>loom-rest-model</artifactId>
    <version>1.0.0-SNAPSHOT</version>
</dependency>
----

== Shared API

[source,xml]
----
<dependency>
    <groupId>io.metaloom.loom</groupId>
    <artifactId>loom-api</artifactId>
    <version>1.0.0-SNAPSHOT</version>
</dependency>
----

*** Add File: /home/defaultuser/workspaces/metaloom/metaloom/website/content/english/docs/loom/containers/index.adoc
---
title: Containers
---

The Loom server is distributed as a Docker image.

== Running with Docker

[source,bash]
----
docker run -d \
  --name loom \
  -p 8092:8092 \
  -p 8091:8091 \
  -p 8989:8989 \
  -e LOOM_DB_HOST=postgres \
  -e LOOM_DB_PASSWORD=secret \
  -e LOOM_INITIAL_PASSWORD=admin123 \
  -v loom-config:/app/config \
  metaloom/loom:latest
----

== Docker Compose

[source,yaml]
----
version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: loom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  loom:
    image: metaloom/loom:latest
    depends_on:
      - postgres
    ports:
      - "8092:8092"
      - "8989:8989"
    environment:
      LOOM_DB_HOST: postgres
      LOOM_DB_PASSWORD: secret
      LOOM_INITIAL_PASSWORD: admin123
----

*** Add File: /home/defaultuser/workspaces/metaloom/metaloom/website/content/english/docs/loom/helm-chart/index.adoc
---
title: Helm Chart
---

The Loom Helm chart is the Kubernetes deployment entry point for running the server in-cluster.

== Location

The chart is available in the `loom/helm` directory of the source repository.

== Typical Use

Use the chart when you want to deploy Loom together with database, ingress, persistent volumes and environment-specific values files in a Kubernetes environment.

== Example

[source,bash]
----
helm upgrade --install loom ./loom/helm \
  --namespace loom \
  --create-namespace \
  --values values.yaml
----