<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.metaloom.loom.service</groupId>
    <artifactId>loom-services</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>loom-service-rest</artifactId>
  <name>MetaLoom // Loom :: Service :: REST API</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-web</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.loom</groupId>
      <artifactId>loom-common</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.loom.service</groupId>
      <artifactId>loom-service-auth-common</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.loom.service</groupId>
      <artifactId>loom-service-auth-jwt</artifactId>
    </dependency>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-auth-oauth2</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.loom.db</groupId>
      <artifactId>loom-db-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.loom.service</groupId>
      <artifactId>loom-service-graphql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.loom.shared</groupId>
      <artifactId>loom-rest-model</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-nodes-common-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-source-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-filter-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-hash-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-dedup-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-thumbnail-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-consistency-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-fingerprint-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-facedetect-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-scene-detection-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-ocr-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-llm-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-tika-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-whisper-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-quality-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-captioning-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.cortex</groupId>
      <artifactId>cortex-loom-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.video</groupId>
      <artifactId>video4j-fingerprint</artifactId>
    </dependency>
    <dependency>
      <groupId>io.metaloom.vertx</groupId>
      <artifactId>vertx-web-openapi-generator</artifactId>
    </dependency>

    <!-- Test -->
    <dependency>
      <groupId>io.metaloom.loom.client</groupId>
      <artifactId>loom-client-rest</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>


  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>com.google.dagger</groupId>
              <artifactId>dagger-compiler</artifactId>
              <version>${dagger.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
