# GENERATED by tools/generate_models.py -- DO NOT EDIT.
"""Mirrors ``io.metaloom.loom.rest.model.media``."""

from __future__ import annotations

from dataclasses import dataclass

from .base import Model


@dataclass
class MediaInfoResponse(Model):
    """Mirrors ``io.metaloom.loom.rest.model.media.MediaInfoResponse``."""

    #: Duration of the video in seconds, as reported by the container. Null when it could not be determined.
    duration: float | None = None
    #: Frame rate in frames per second. Needed to place a detection's frameNumber on a timeline.
    frame_rate: float | None = None
    #: Width of the first video stream in pixels.
    width: int | None = None
    #: Height of the first video stream in pixels.
    height: int | None = None
    #: Codec of the first video stream, e.g. h264. The stream route can only remux a subset of these.
    video_codec: str | None = None
    #: Codec of the first audio stream, e.g. ac3, or null when the file carries no audio.
    audio_codec: str | None = None
    #: True when the stream route can serve this file without a full re-encode.
    streamable: bool = False


@dataclass
class MediaTokenResponse(Model):
    """Mirrors ``io.metaloom.loom.rest.model.media.MediaTokenResponse``."""

    #: The signed media token, to be appended as the mt query parameter on poster and stream URLs.
    token: str | None = None
    #: Lifetime of the token in seconds. Mint a new one rather than caching this past its expiry.
    expires_in: int = 0


@dataclass
class StreamStartResponse(Model):
    """Mirrors ``io.metaloom.loom.rest.model.media.StreamStartResponse``."""

    #: The offset in seconds that was asked for.
    requested: float | None = None
    #: The offset a stream requested at that point will really begin at: the keyframe at or before it. Treat
    #: it as the origin of the player's clock. Do NOT send it back as the stream's 't' - keep asking for the
    #: offset you wanted, or the seek snaps a second time and lands a further group of pictures back.
    start: float | None = None
