# GENERATED by tools/generate_models.py -- DO NOT EDIT.
"""Mirrors ``io.metaloom.loom.rest.model.memory``."""

from __future__ import annotations

from dataclasses import dataclass, field

from .base import CreatorEditorResponse, ListResponse, MetaModel


@dataclass
class MemoryDenyRuleCreateRequest(MetaModel):
    """Mirrors ``io.metaloom.loom.rest.model.memory.MemoryDenyRuleCreateRequest``."""

    name: str | None = None
    pattern: str | None = None
    message: str | None = None
    enabled: bool | None = None


@dataclass
class MemoryDenyRuleListResponse(ListResponse):
    """Mirrors ``io.metaloom.loom.rest.model.memory.MemoryDenyRuleListResponse``."""

    #: Array which contains the found elements.
    data: list[MemoryDenyRuleResponse] = field(default_factory=list)


@dataclass
class MemoryDenyRuleResponse(CreatorEditorResponse):
    """Mirrors ``io.metaloom.loom.rest.model.memory.MemoryDenyRuleResponse``."""

    name: str | None = None
    pattern: str | None = None
    message: str | None = None
    enabled: bool | None = None


@dataclass
class MemoryDenyRuleUpdateRequest(MetaModel):
    """Mirrors ``io.metaloom.loom.rest.model.memory.MemoryDenyRuleUpdateRequest``."""

    name: str | None = None
    pattern: str | None = None
    message: str | None = None
    enabled: bool | None = None
