# GENERATED by tools/generate_models.py -- DO NOT EDIT.
"""Mirrors ``io.metaloom.loom.rest.model.noderesult``."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .base import CreatorEditorResponse, ListResponse, MetaModel


@dataclass
class NodeResultCreateRequest(MetaModel):
    """Mirrors ``io.metaloom.loom.rest.model.noderesult.NodeResultCreateRequest``."""

    node_kind: str | None = None
    node_id: str | None = None
    producer_version: str | None = None
    state: str | None = None
    origin: str | None = None
    reason: str | None = None
    duration_ms: int | None = None
    result_ref: dict[str, Any] | None = None


@dataclass
class NodeResultListResponse(ListResponse):
    """Mirrors ``io.metaloom.loom.rest.model.noderesult.NodeResultListResponse``."""

    #: Array which contains the found elements.
    data: list[NodeResultResponse] = field(default_factory=list)


@dataclass
class NodeResultResponse(CreatorEditorResponse):
    """Mirrors ``io.metaloom.loom.rest.model.noderesult.NodeResultResponse``."""

    asset_uuid: str | None = None
    node_kind: str | None = None
    node_id: str | None = None
    producer_version: str | None = None
    state: str | None = None
    origin: str | None = None
    reason: str | None = None
    duration_ms: int | None = None
    result_ref: dict[str, Any] | None = None
