# GENERATED by tools/generate_models.py -- DO NOT EDIT.
"""Mirrors ``io.metaloom.loom.rest.model.person``."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .base import CreatorEditorResponse, ListResponse, Model


@dataclass
class PersonCreateRequest(Model):
    """Mirrors ``io.metaloom.loom.rest.model.person.PersonCreateRequest``."""

    #: The alias of the person.
    alias: str | None = None
    #: The first name of the person.
    firstname: str | None = None
    #: The last name of the person.
    lastname: str | None = None
    #: UUID of the primary gallery image.
    primary_image_uuid: str | None = None
    #: Additional custom meta properties for the element.
    meta: dict[str, Any] | None = None


@dataclass
class PersonListResponse(ListResponse):
    """Mirrors ``io.metaloom.loom.rest.model.person.PersonListResponse``."""

    #: Array which contains the found elements.
    data: list[PersonResponse] = field(default_factory=list)


@dataclass
class PersonResponse(CreatorEditorResponse):
    """Mirrors ``io.metaloom.loom.rest.model.person.PersonResponse``."""

    #: The alias of the person
    alias: str | None = None
    #: The first name of the person
    firstname: str | None = None
    #: The last name of the person
    lastname: str | None = None
    #: UUID of the primary gallery image
    primary_image_uuid: str | None = None


@dataclass
class PersonUpdateRequest(Model):
    """Mirrors ``io.metaloom.loom.rest.model.person.PersonUpdateRequest``."""

    #: The alias of the person.
    alias: str | None = None
    #: The first name of the person.
    firstname: str | None = None
    #: The last name of the person.
    lastname: str | None = None
    #: UUID of the primary gallery image.
    primary_image_uuid: str | None = None
    #: Additional custom meta properties for the element.
    meta: dict[str, Any] | None = None
