# GENERATED by tools/generate_models.py -- DO NOT EDIT.
"""Mirrors ``io.metaloom.loom.rest.model.role``."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .base import CreatorEditorResponse, ListResponse, Model, NamedReference
from .enums import RolePermission


@dataclass
class RoleCreateRequest(Model):
    """Mirrors ``io.metaloom.loom.rest.model.role.RoleCreateRequest``."""

    #: The name of the new role
    name: str | None = None
    #: Additional custom meta properties for the element.
    meta: dict[str, Any] | None = None
    #: A list of permissions that are granted by the role.
    permissions: list[RolePermission] = field(default_factory=list)


@dataclass
class RoleListResponse(ListResponse):
    """Mirrors ``io.metaloom.loom.rest.model.role.RoleListResponse``."""

    #: Array which contains the found elements.
    data: list[RoleResponse] = field(default_factory=list)


@dataclass
class RoleReference(NamedReference):
    """Mirrors ``io.metaloom.loom.rest.model.role.RoleReference``."""



@dataclass
class RoleResponse(CreatorEditorResponse):
    """Mirrors ``io.metaloom.loom.rest.model.role.RoleResponse``."""

    #: The name of the role
    name: str | None = None
    #: A list of permissions that are granted by the role.
    permissions: list[RolePermission] = field(default_factory=list)


@dataclass
class RoleUpdateRequest(Model):
    """Mirrors ``io.metaloom.loom.rest.model.role.RoleUpdateRequest``."""

    #: The new name of the role.
    name: str | None = None
    #: Additional custom meta properties for the element.
    meta: dict[str, Any] | None = None
    #: A list of permissions that are granted by the role.
    permissions: list[RolePermission] = field(default_factory=list)
