# GENERATED by tools/generate_models.py -- DO NOT EDIT.
"""Mirrors ``io.metaloom.loom.rest.model.task``."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from .base import CreatorEditorResponse, ListResponse, MetaModel
from .enums import TaskPriority, TaskStatus

if TYPE_CHECKING:
    from .comment import CommentResponse


@dataclass
class TaskCreateRequest(MetaModel):
    """Mirrors ``io.metaloom.loom.rest.model.task.TaskCreateRequest``."""

    title: str | None = None
    description: str | None = None
    priority: TaskPriority | None = None
    task_status: TaskStatus | None = None
    due_date: str | None = None


@dataclass
class TaskListResponse(ListResponse):
    """Mirrors ``io.metaloom.loom.rest.model.task.TaskListResponse``."""

    #: Array which contains the found elements.
    data: list[TaskResponse] = field(default_factory=list)


@dataclass
class TaskResponse(CreatorEditorResponse):
    """Mirrors ``io.metaloom.loom.rest.model.task.TaskResponse``."""

    title: str | None = None
    description: str | None = None
    priority: TaskPriority | None = None
    task_status: TaskStatus | None = None
    #: ISO8601 formatted due date string.
    due_date: str | None = None
    comments: list[CommentResponse] = field(default_factory=list)


@dataclass
class TaskUpdateRequest(MetaModel):
    """Mirrors ``io.metaloom.loom.rest.model.task.TaskUpdateRequest``."""

    title: str | None = None
    description: str | None = None
    priority: TaskPriority | None = None
    task_status: TaskStatus | None = None
    due_date: str | None = None
