FROM eclipse-temurin:25-jre-alpine

ENV LOOM_AUTH_KEYSTORE_PATH=/keystore/keystore.jks
ENV LOOM_BINARY_DIR=/uploads
ENV LOOM_TEMP_DIR=/tmp
ENV HOME=/loom
ENV JAVA_TOOL_OPTIONS="-Xms512m -Xmx512m"

EXPOSE 8092
EXPOSE 8091

USER root
RUN adduser -D -u 1000 -G root -h /loom loom && \
    mkdir /uploads   && chown 1000:0 /uploads  -R && chmod 770 /uploads  && \
    mkdir /plugins   && chown 1000:0 /plugins  -R && chmod 770 /plugins  && \
    mkdir /keystore  && chown 1000:0 /keystore -R && chmod 770 /keystore && \
    mkdir /config    && chown 1000:0 /config   -R && chmod 770 /config && ln -s /config /loom/config && \
    mkdir /loom/data && \
    chown 1000:0 /loom -R && \
    chmod 770 /loom -R
ADD --chown=1000:0 ./loom/containers/demo/target/loom-demo.jar /loom/loom.jar
ADD --chown=1000:0 ./loom-ui/build /loom/ui

USER loom
WORKDIR /loom
VOLUME /uploads
VOLUME /plugins
VOLUME /keystore
VOLUME /config

CMD [ "java", "-Djna.tmpdir=/tmp/.jna", "-Duser.dir=/loom", "-jar" , "loom.jar"]
