{{- if and .Values.loom.token (not .Values.loom.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cortex.tokenSecretName" . }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.loom.token | quote }}
{{- end }}
