<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.metaloom.loom.db</groupId>
        <artifactId>loom-db</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>loom-db-api-test</artifactId>
    <name>MetaLoom // Loom :: DB :: API Test</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.metaloom</groupId>
                <artifactId>bom</artifactId>
                <type>pom</type>
                <scope>import</scope>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>io.metaloom.loom.shared</groupId>
            <artifactId>loom-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.metaloom.loom.db</groupId>
            <artifactId>loom-db-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-rx-java3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>io.metaloom.loom.test</groupId>
            <artifactId>loom-test-env</artifactId>
        </dependency>
    </dependencies>
</project>
