package io.metaloom.loom.db.jooq;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.Test;

import io.metaloom.loom.db.model.library.Library;
import io.metaloom.loom.db.model.user.User;
import io.metaloom.loom.db.page.Page;

/**
 * Pins the UUIDv7 switch made in migration V2.104.
 *
 * <p>
 * The REST list endpoints page with a keyset cursor over the uuid column, so the uuid is the default sort order of every collection Loom serves. That
 * only produces a sensible list if the keys are time ordered, which makes "are they still time ordered" a schema invariant rather than a detail of
 * one migration.
 * </p>
 */
public class UUIDv7SchemaTest extends AbstractJooqTest {

	/**
	 * The regression this really guards: a new table added by copying an older migration, bringing <code>uuid_generate_v4()</code> along with it. That
	 * table would then be the one collection in the product whose list order is random, and nothing else in the suite would notice.
	 */
	@Test
	public void testEveryUuidDefaultIsUuidV7() {
		List<String> offenders = context.ctx()
			.resultQuery("""
				SELECT c.relname || '.' || a.attname || ' -> ' || pg_get_expr(d.adbin, d.adrelid)
				  FROM pg_attrdef d
				  JOIN pg_class c ON c.oid = d.adrelid
				  JOIN pg_namespace n ON n.oid = c.relnamespace
				  JOIN pg_attribute a ON a.attrelid = d.adrelid AND a.attnum = d.adnum
				 WHERE n.nspname = current_schema()
				   AND c.relkind = 'r'
				   AND format_type(a.atttypid, a.atttypmod) = 'uuid'
				   AND pg_get_expr(d.adbin, d.adrelid) NOT LIKE '%uuidv7%'
				 ORDER BY 1
				""")
			.fetchInto(String.class);

		assertThat(offenders)
			.as("every generated uuid column must default to uuidv7() - see V2.104")
			.isEmpty();
	}

	/**
	 * Sanity check that the default is not merely declared but reachable: the DAO leaves the column unset, so this fails if anything in the insert
	 * path started supplying a uuid of its own.
	 */
	@Test
	public void testDatabaseGeneratedKeysAreVersion7() {
		User user = dummyUser();
		for (int i = 0; i < 20; i++) {
			Library library = libraryDao().createLibrary(user, "v7_version_" + i);
			libraryDao().store(library);
			assertThat(library.getUuid().version())
				.as("uuid generated by the database default")
				.isEqualTo(7);
		}
	}

	/**
	 * The behaviour the switch was made for, asserted end to end through the DAO rather than against the generator.
	 *
	 * <p>
	 * Filtered to the rows this test created, because the pooled database arrives pre-populated - the rows already in the table are older fixtures and
	 * say nothing about insertion order here.
	 * </p>
	 */
	@Test
	public void testPagingReturnsRowsInCreationOrder() {
		User user = dummyUser();
		String prefix = "v7_order_" + UUID.randomUUID() + "_";
		List<String> created = new ArrayList<>();
		for (int i = 0; i < 50; i++) {
			Library library = libraryDao().createLibrary(user, prefix + String.format("%03d", i));
			libraryDao().store(library);
			created.add(library.getName());
		}

		List<String> paged = new ArrayList<>();
		UUID cursor = null;
		while (true) {
			Page<Library> page = libraryDao().loadPage(cursor, 10, null, null, null);
			if (page.isEmpty()) {
				break;
			}
			for (Library library : page) {
				if (library.getName() != null && library.getName().startsWith(prefix)) {
					paged.add(library.getName());
				}
			}
			cursor = page.last().getUuid();
		}

		assertThat(paged)
			.as("the default page order must be the order the rows were created in")
			.containsExactlyElementsOf(created);
	}
}
