{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loom.auth.secretName" . }}
  labels:
    {{- include "loom.labels" . | nindent 4 }}
type: Opaque
stringData:
  initial-password: {{ .Values.auth.initialPassword | quote }}
{{- end }}
{{- if and (not .Values.postgresql.enabled) (not .Values.database.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loom.database.secretName" . }}
  labels:
    {{- include "loom.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.database.password | quote }}
{{- end }}
