package io.metaloom.loom.mcp.tool.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.ByteArrayInputStream;
import java.util.List;
import java.util.Set;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

import io.metaloom.loom.api.options.ImageGenToolOptions;
import io.metaloom.loom.api.options.LoomOptions;
import io.metaloom.loom.db.dagger.DaoCollection;
import io.metaloom.loom.db.model.asset.Asset;
import io.metaloom.loom.db.model.asset.AssetBinary;
import io.metaloom.loom.db.model.asset.AssetBinaryDao;
import io.metaloom.loom.db.model.asset.AssetDao;
import io.metaloom.loom.mcp.imagegen.ImageEditClient;
import io.metaloom.loom.mcp.model.MCPCallerContext;
import io.metaloom.loom.rest.service.impl.BinaryStorageResolver;
import io.metaloom.loom.rest.service.impl.ProducedAssetIngestor;
import io.metaloom.loom.storage.BinaryStorage;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;

/**
 * {@code generate_image}, the tool that draws a picture into the chat.
 *
 * <p>
 * Two things are pinned here and nothing else would catch either. First the <b>envelope</b>: the
 * model never sees the visual, so a dropped {@code payload.kind} is a grey box in the UI and a
 * conversation that reads as if it worked. Second the <b>ingest</b>: the generated bytes have to
 * become a real asset, because a base64 PNG cannot travel in a visual — {@code VisualExtractor}
 * discards anything over 32 KB — so "it returned an asset uuid" is the feature, not an implementation
 * detail.
 * </p>
 */
public class GenerateImageToolTest {

	private static final UUID USER_UUID = UUID.fromString("11111111-0000-0000-0000-000000000001");
	private static final UUID LIBRARY_UUID = UUID.fromString("22222222-0000-0000-0000-000000000002");
	private static final UUID INPUT_UUID = UUID.fromString("33333333-0000-0000-0000-000000000003");
	private static final UUID RESULT_UUID = UUID.fromString("44444444-0000-0000-0000-00000000f00d");
	private static final UUID POOL_UUID = UUID.fromString("55555555-0000-0000-0000-000000000005");

	private static final byte[] INPUT_BYTES = "input-image-bytes".getBytes();
	private static final byte[] GENERATED_PNG = "generated-png-bytes".getBytes();

	private DaoCollection daos;
	private AssetDao assetDao;
	private AssetBinaryDao assetBinaryDao;
	private ImageEditClient client;
	private ProducedAssetIngestor ingestor;
	private BinaryStorageResolver storageResolver;
	private LoomOptions loomOptions;

	private final MCPCallerContext caller = new MCPCallerContext(USER_UUID, "tester", Set.of(), null, null);

	@BeforeEach
	public void setup() throws Exception {
		daos = mock(DaoCollection.class);
		assetDao = mock(AssetDao.class);
		assetBinaryDao = mock(AssetBinaryDao.class);
		when(daos.assetDao()).thenReturn(assetDao);
		when(daos.assetBinaryDao()).thenReturn(assetBinaryDao);

		client = mock(ImageEditClient.class);
		when(client.generate(any(), any(), any(), any(), any(), any())).thenReturn(GENERATED_PNG);

		// Built BEFORE the stubbing that returns it: constructing a mock inside a when(...) argument
		// leaves Mockito mid-stub and every test in the class fails with UnfinishedStubbingException.
		Asset result = resultAsset();
		ingestor = mock(ProducedAssetIngestor.class);
		when(ingestor.ingest(any(), any(), any(), any(), any(), any())).thenReturn(result);

		storageResolver = mock(BinaryStorageResolver.class);

		loomOptions = new LoomOptions();
		// The tool's own Dagger module gates on `enabled`; once constructed it just runs, so the
		// flag is irrelevant here and the library is what matters.
		loomOptions.setImageGenTool(new ImageGenToolOptions().setLibraryUuid(LIBRARY_UUID.toString()));
	}

	private GenerateImageTool tool() {
		return new GenerateImageTool(daos, client, ingestor, storageResolver, loomOptions);
	}

	private Asset resultAsset() {
		Asset asset = mock(Asset.class);
		when(asset.getUuid()).thenReturn(RESULT_UUID);
		when(asset.getFilename()).thenReturn("generated-a-red-apple-7.png");
		when(asset.getSize()).thenReturn((long) GENERATED_PNG.length);
		return asset;
	}

	/** An image asset in the catalogue whose bytes are readable from storage. */
	private Asset catalogHoldsAnImage() throws Exception {
		Asset asset = mock(Asset.class);
		when(asset.getUuid()).thenReturn(INPUT_UUID);
		when(asset.getFilename()).thenReturn("boy.jpg");
		when(asset.getMimeType()).thenReturn("image/jpeg");
		when(asset.getSize()).thenReturn((long) INPUT_BYTES.length);
		when(assetDao.loadById(any())).thenReturn(asset);

		AssetBinary binary = mock(AssetBinary.class);
		when(binary.getPath()).thenReturn("/pool/ab/cd/ef/boy.jpg");
		when(binary.getPoolUuid()).thenReturn(POOL_UUID);
		when(binary.getLibraryUuid()).thenReturn(LIBRARY_UUID);
		when(assetBinaryDao.loadPrimaryByAssetUuid(INPUT_UUID)).thenReturn(binary);

		BinaryStorage storage = mock(BinaryStorage.class);
		when(storage.exists(any())).thenReturn(true);
		when(storage.size(any())).thenReturn((long) INPUT_BYTES.length);
		when(storage.read(any(), anyLong(), anyLong())).thenReturn(new ByteArrayInputStream(INPUT_BYTES));
		when(storageResolver.forPool(any())).thenReturn(storage);
		return asset;
	}

	private static String text(JsonObject result) {
		JsonArray content = result.getJsonArray("content");
		assertNotNull(content, "The tool result should carry content");
		return content.getJsonObject(0).getString("text");
	}

	private static JsonObject onlyVisual(JsonObject result) {
		JsonArray visuals = result.getJsonArray("visuals");
		assertNotNull(visuals, "The result should carry a visual - it is how the picture reaches the chat");
		assertEquals(1, visuals.size());
		return visuals.getJsonObject(0);
	}

	// ------------------------------------------------------------------------------------------
	// Descriptor
	// ------------------------------------------------------------------------------------------

	@Test
	public void testDescriptor() {
		var descriptor = tool().descriptor();
		assertEquals("generate_image", descriptor.name());

		// All four, and in this order. GENERATE_MCP_IMAGE sits ALONGSIDE the base permissions and
		// never instead of them, so granting it alone can never widen what a user may read or create.
		assertEquals(List.of("READ_ASSET", "READ_ASSET_BINARY", "CREATE_ASSET", "GENERATE_MCP_IMAGE"),
			descriptor.requiredPermissions());

		// It stamps a creator on a new asset, so it must not be dispatchable without a caller.
		assertTrue(descriptor.requiresIdentity(), "generate_image writes an asset and must be identity-scoped");

		JsonObject schema = descriptor.inputSchema();
		assertEquals(List.of("prompt"), schema.getJsonArray("required").getList(),
			"only the prompt is required - everything else has a sensible absence");
		JsonObject properties = schema.getJsonObject("properties");
		assertEquals("array", properties.getJsonObject("assetIds").getString("type"));
		assertNotNull(properties.getJsonObject("maskPrompt"));
	}

	@Test
	public void testUnauthenticatedCallersAreRefused() {
		var result = tool().execute(new JsonObject().put("prompt", "a red apple"), MCPCallerContext.ANONYMOUS);
		assertTrue(result.failed(), "an anonymous caller must not be able to create an asset");
	}

	@Test
	public void testTheArgumentOnlyOverloadCannotRun() {
		// Belt and braces: an identity-scoped tool gets no EventBus address, so this is unreachable
		// by construction - but it must not silently succeed if that ever changes.
		assertTrue(tool().execute(new JsonObject().put("prompt", "a red apple")).failed());
	}

	// ------------------------------------------------------------------------------------------
	// Text-to-image
	// ------------------------------------------------------------------------------------------

	@Test
	public void testTextToImageIngestsTheResultAndShowsIt() throws Exception {
		JsonObject result = tool().execute(new JsonObject().put("prompt", "a red apple").put("seed", 7), caller).result();

		// The bytes the sidecar produced are what gets ingested, under the caller's identity.
		verify(ingestor).ingest(eq(USER_UUID), eq(LIBRARY_UUID), eq(GENERATED_PNG), any(), eq("image/png"), eq("mcp:generate_image"));

		JsonObject visual = onlyVisual(result);
		assertEquals("asset-viewer", visual.getString("type"),
			"reusing show_asset's visual type is what makes this render with no UI change");
		JsonObject payload = visual.getJsonObject("payload");
		assertEquals(RESULT_UUID.toString(), payload.getString("assetUuid"));
		assertEquals("image/png", payload.getString("mimeType"));
		assertEquals("image", payload.getString("kind"), "a missing kind renders as a grey box");
		assertEquals("a red apple", payload.getString("caption"));

		// The text stands alone: a client that cannot render the visual can still say what happened.
		assertTrue(text(result).contains(RESULT_UUID.toString()), "the text must name the asset: " + text(result));
	}

	@Test
	public void testTextToImageSendsNoInputImages() throws Exception {
		tool().execute(new JsonObject().put("prompt", "a red apple"), caller).result();

		ArgumentCaptor<List<byte[]>> images = ArgumentCaptor.forClass(List.class);
		verify(client).generate(eq("a red apple"), images.capture(), any(), any(), any(), any());
		assertTrue(images.getValue().isEmpty());
	}

	/**
	 * Without an input asset to inherit a library from, and with none configured, there is nowhere
	 * to file the result. That is a deployment gap the user can fix, so it is said in words rather
	 * than failed - the model repeating the call would not help.
	 */
	@Test
	public void testTextToImageWithoutALibraryExplainsItself() throws Exception {
		loomOptions.setImageGenTool(new ImageGenToolOptions());

		JsonObject result = tool().execute(new JsonObject().put("prompt", "a red apple"), caller).result();

		assertTrue(text(result).contains("LOOM_MCP_IMAGEGEN_LIBRARY"), text(result));
		assertNull(result.getJsonArray("visuals"), "nothing was generated, so there is nothing to show");
		verify(client, never()).generate(any(), any(), any(), any(), any(), any());
	}

	// ------------------------------------------------------------------------------------------
	// Editing and composing
	// ------------------------------------------------------------------------------------------

	@Test
	public void testEditingSendsTheAssetBytesAndTheMaskPrompt() throws Exception {
		catalogHoldsAnImage();

		JsonObject arguments = new JsonObject()
			.put("prompt", "give him dark brown hair")
			.put("assetIds", new JsonArray().add(INPUT_UUID.toString()))
			.put("maskPrompt", "the boy's hair");

		JsonObject result = tool().execute(arguments, caller).result();

		ArgumentCaptor<List<byte[]>> images = ArgumentCaptor.forClass(List.class);
		verify(client).generate(eq("give him dark brown hair"), images.capture(), eq("the boy's hair"), any(), any(), any());
		assertEquals(1, images.getValue().size());
		assertArrayEqualsish(INPUT_BYTES, images.getValue().get(0));

		assertTrue(text(result).contains("changing only the boy's hair"), text(result));
	}

	/**
	 * An edit is filed next to what it was made from, which is where anyone would look for it -
	 * not in whatever default library the deployment happens to name.
	 */
	@Test
	public void testAnEditIsFiledInTheInputsLibrary() throws Exception {
		catalogHoldsAnImage();
		loomOptions.setImageGenTool(new ImageGenToolOptions().setLibraryUuid(UUID.randomUUID().toString()));

		JsonObject arguments = new JsonObject()
			.put("prompt", "make it night")
			.put("assetIds", new JsonArray().add(INPUT_UUID.toString()));
		tool().execute(arguments, caller).result();

		verify(ingestor).ingest(any(), eq(LIBRARY_UUID), any(), any(), any(), any());
	}

	@Test
	public void testTheInputAssetsAreReferencedAlongsideTheResult() throws Exception {
		catalogHoldsAnImage();

		JsonObject arguments = new JsonObject()
			.put("prompt", "make it night")
			.put("assetIds", new JsonArray().add(INPUT_UUID.toString()));
		JsonObject result = tool().execute(arguments, caller).result();

		JsonArray references = result.getJsonArray("references");
		assertEquals(2, references.size(), "the generated asset and the one it came from");
		assertEquals(RESULT_UUID.toString(), references.getJsonObject(0).getString("uuid"), "the result comes first");
		assertEquals(INPUT_UUID.toString(), references.getJsonObject(1).getString("uuid"));
	}

	@Test
	public void testTooManyInputImagesIsAnAnswerNotAFailure() throws Exception {
		catalogHoldsAnImage();
		loomOptions.getImageGenTool().setMaxImages(2);

		JsonArray ids = new JsonArray();
		for (int i = 0; i < 3; i++) {
			ids.add(INPUT_UUID.toString());
		}
		JsonObject result = tool().execute(new JsonObject().put("prompt", "combine").put("assetIds", ids), caller).result();

		assertTrue(text(result).contains("at most 2"), text(result));
		verify(client, never()).generate(any(), any(), any(), any(), any(), any());
	}

	@Test
	public void testAMissingInputAssetIsAnAnswerNotAFailure() throws Exception {
		when(assetDao.loadById(any())).thenReturn(null);

		JsonObject result = tool().execute(new JsonObject()
			.put("prompt", "make it night")
			.put("assetIds", new JsonArray().add(INPUT_UUID.toString())), caller).result();

		assertTrue(text(result).contains("Asset not found"), text(result));
		assertNull(result.getJsonArray("visuals"));
	}

	/** Handing a PDF to an image model wastes a GPU minute to produce nonsense. */
	@Test
	public void testANonImageInputIsRejectedBeforeTheSidecarIsCalled() throws Exception {
		Asset document = mock(Asset.class);
		when(document.getUuid()).thenReturn(INPUT_UUID);
		when(document.getFilename()).thenReturn("contract.pdf");
		when(document.getMimeType()).thenReturn("application/pdf");
		when(assetDao.loadById(any())).thenReturn(document);

		JsonObject result = tool().execute(new JsonObject()
			.put("prompt", "make it night")
			.put("assetIds", new JsonArray().add(INPUT_UUID.toString())), caller).result();

		assertTrue(text(result).contains("Not an image"), text(result));
		verify(client, never()).generate(any(), any(), any(), any(), any(), any());
	}

	/**
	 * A sidecar that is down, or still loading 33 GB of weights, is the most likely failure in
	 * production. It has to come back as something the model can relay, not as a dead turn.
	 */
	@Test
	public void testASidecarFailureIsReportedAsText() throws Exception {
		when(client.generate(any(), any(), any(), any(), any(), any()))
			.thenThrow(new RuntimeException("Could not reach the image sidecar at localhost:9230 - is it running?"));

		var future = tool().execute(new JsonObject().put("prompt", "a red apple"), caller);
		assertFalse(future.failed(), "a sidecar outage must not kill the turn");
		assertTrue(text(future.result()).contains("could not be generated"), text(future.result()));
		assertTrue(text(future.result()).contains("9230"), "the reason should survive: " + text(future.result()));
	}

	// ------------------------------------------------------------------------------------------

	@Test
	public void testTheGeneratedFilenameDescribesThePrompt() {
		assertEquals("generated-a-red-apple-on-a-table-7.png", GenerateImageTool.filename("A red apple, on a table!", 7));
		assertEquals("generated-image.png", GenerateImageTool.filename("!!!", null),
			"a prompt with nothing nameable in it still needs a filename");
		assertTrue(GenerateImageTool.filename("x".repeat(500), null).length() < 80, "a long prompt must not become a long filename");
	}

	private static void assertArrayEqualsish(byte[] expected, byte[] actual) {
		assertEquals(new String(expected), new String(actual));
	}
}
