<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>bom</artifactId>

    <parent>
        <groupId>io.metaloom</groupId>
        <artifactId>metaloom-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <name>MetaLoom // BOM</name>
    <packaging>pom</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <dagger.version>2.57.2</dagger.version>
        <hazelcast.version>5.3.8</hazelcast.version>
        <tika.version>3.2.2</tika.version>
        <pico-cli.version>4.7.5</pico-cli.version>
        <aws.sdk.version>2.29.70</aws.sdk.version>
        <jackson.version>2.18.2</jackson.version>
        <jackson-databind.version>2.18.2</jackson-databind.version>
        <okhttp.version>4.12.0</okhttp.version>
        <postgres.driver.version>42.7.10</postgres.driver.version>
        <spring.security.version>6.5.10</spring.security.version>
        <video4j.version>2.0.0-SNAPSHOT</video4j.version>

        <!-- Sonar /  Maven -->
        <jacoco.version>0.8.8</jacoco.version>
        <sonar.version>3.9.1.2184</sonar.version>

        <!-- Logging -->
        <logback.classic.version>1.5.19</logback.classic.version>
        <slf4j.version>2.0.7</slf4j.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <!-- MetaLoom -->
            <dependency>
                <groupId>io.metaloom.loom.shared</groupId>
                <artifactId>loom-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.loom.shared</groupId>
                <artifactId>loom-rest-model</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.loom.shared</groupId>
                <artifactId>loom-rest-model-test</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.loom.shared</groupId>
                <artifactId>loom-db-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.loom.db</groupId>
                <artifactId>loom-db-api-test</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.metaloom.loom.test</groupId>
                <artifactId>loom-test-env</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.loom</groupId>
                <artifactId>loom-fixture</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-cli</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- Cortex Node Descriptor API modules -->
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-nodes-common-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-source-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-filter-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-hash-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-dedup-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-thumbnail-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-consistency-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-fingerprint-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-facedetect-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-scene-detection-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-ocr-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-llm-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-tika-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-whisper-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-quality-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-captioning-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.cortex</groupId>
                <artifactId>cortex-loom-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- DB -->
            <dependency>
                <artifactId>vertx-mysql-client</artifactId>
                <groupId>io.vertx</groupId>
                <version>${vertx.version}</version>
            </dependency>
            <dependency>
                <artifactId>vertx-pg-client</artifactId>
                <groupId>io.vertx</groupId>
                <version>${vertx.version}</version>
            </dependency>

            <!-- JDBC -->
            <dependency>
                <groupId>com.mchange</groupId>
                <artifactId>c3p0</artifactId>
                <version>0.12.0</version>
            </dependency>
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgres.driver.version}</version>
            </dependency>
            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-sql-client</artifactId>
                <version>${vertx.version}</version>
            </dependency>

            <!-- REST API -->
            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-web-openapi</artifactId>
                <version>${vertx.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.vertx</groupId>
                <artifactId>vertx-web-openapi</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.vertx</groupId>
                <artifactId>vertx-web-openapi-generator</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.vertx</groupId>
                <artifactId>vertx-web-openapi-core</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>

            <!-- Apache Avro -->
            <dependency>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro</artifactId>
                <version>${avro.version}</version>
            </dependency>
            <dependency>
                <groupId>org.xerial.snappy</groupId>
                <artifactId>snappy-java</artifactId>
                <version>1.1.10.7</version>
            </dependency>


            <!-- Dagger -->
            <dependency>
                <groupId>com.google.dagger</groupId>
                <artifactId>dagger</artifactId>
                <version>${dagger.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.dagger</groupId>
                <artifactId>dagger-compiler</artifactId>
                <version>${dagger.version}</version>
                <optional>true</optional>
            </dependency>

            <!-- Flyway -->
            <dependency>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-core</artifactId>
                <version>9.16.1</version>
            </dependency>
            <!-- Override transitive jackson-dataformat-toml from flyway
                        (CVE-2023-3894) -->
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-toml</artifactId>
                <version>${jackson.version}</version>
            </dependency>

            <!-- Override transitive commons-compress (CVE-2023-42503,
            CVE-2024-25710, CVE-2024-26308). 1.28.0 aligns with Tika 3.2.2. -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-compress</artifactId>
                <version>1.28.0</version>
            </dependency>

            <!-- Utilities -->
            <!-- 2.16.0+ required by commons-compress 1.27.1 (ChecksumInputStream) used by Tika 3.x -->
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>2.20.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-math3</artifactId>
                <version>3.6.1</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>32.1.3-jre</version>
            </dependency>
            <dependency>
                <groupId>commons-cli</groupId>
                <artifactId>commons-cli</artifactId>
                <version>1.6.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.18.0</version>
            </dependency>
            <dependency>
                <groupId>commons-codec</groupId>
                <artifactId>commons-codec</artifactId>
                <version>1.16.0</version>
            </dependency>

            <!-- UUID -->
            <dependency>
                <groupId>io.hypersistence</groupId>
                <artifactId>hypersistence-tsid</artifactId>
                <version>2.0.0</version>
            </dependency>

            <!-- RX -->
            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-rx-java3</artifactId>
                <version>${vertx.version}</version>
            </dependency>
            <dependency>
                <groupId>io.reactivex.rxjava3</groupId>
                <artifactId>rxjava</artifactId>
                <version>3.1.6</version>
            </dependency>

            <!-- S3 -->
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>s3</artifactId>
                <version>${aws.sdk.version}</version>
            </dependency>

            <!-- Vert.x -->
            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-web</artifactId>
                <version>${vertx.version}</version>
            </dependency>
            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-auth-oauth2</artifactId>
                <version>${vertx.version}</version>
            </dependency>

            <!-- Filtering -->
            <dependency>
                <groupId>io.metaloom.filter</groupId>
                <artifactId>lhs-filter</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>

            <!-- LLM -->
            <dependency>
                <groupId>io.metaloom.utils</groupId>
                <artifactId>genai-utils</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>

            <!-- jOOQ / persistance -->
            <dependency>
                <groupId>javax.persistence</groupId>
                <artifactId>javax.persistence-api</artifactId>
                <version>2.2</version>
            </dependency>

            <!-- Logger -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback.classic.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-core</artifactId>
                <version>${logback.classic.version}</version>
            </dependency>

            <!--
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>2.22.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-slf4j-impl</artifactId>
                <version>2.22.0</version>
            </dependency>
            -->

            <!-- Metrics -->
            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-micrometer-metrics</artifactId>
                <version>${vertx.version}</version>
            </dependency>
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-registry-prometheus</artifactId>
                <version>1.14.6</version>
            </dependency>

            <!-- Test Tools -->
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>3.27.7</version>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>5.23.0</version>
            </dependency>
            <dependency>
                <groupId>com.jayway.jsonpath</groupId>
                <artifactId>json-path</artifactId>
                <version>2.9.0</version>
            </dependency>
            <dependency>
                <groupId>org.skyscreamer</groupId>
                <artifactId>jsonassert</artifactId>
                <version>1.3.0</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.test</groupId>
                <artifactId>testdatabase-provider-junit5</artifactId>
                <version>0.1.5-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>6.0.3</version>
            </dependency>

            <!-- Testcontainer -->
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers</artifactId>
                <version>1.17.6</version>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>1.17.6</version>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>postgresql</artifactId>
                <version>1.17.6</version>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>elasticsearch</artifactId>
                <version>1.17.6</version>
            </dependency>

            <!-- ES client -->
            <dependency>
                <groupId>io.metaloom.elasticsearch</groupId>
                <artifactId>elasticsearch-client</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>

            <!-- Hazelcast -->
            <dependency>
                <groupId>com.hazelcast</groupId>
                <artifactId>hazelcast</artifactId>
                <version>${hazelcast.version}</version>
            </dependency>
            <dependency>
                <groupId>com.hazelcast</groupId>
                <artifactId>hazelcast-kubernetes</artifactId>
                <version>2.2.3</version>
            </dependency>

            <!-- Netty -->
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport-native-epoll</artifactId>
                <classifier>linux-x86_64</classifier>
                <version>${netty.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-buffer</artifactId>
                <version>${netty.version}</version>
            </dependency>
            <dependency>
                <artifactId>netty-codec-http2</artifactId>
                <groupId>io.netty</groupId>
                <version>${netty.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-handler-proxy</artifactId>
                <version>${netty.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport-native-unix-common</artifactId>
                <version>${netty.version}</version>
            </dependency>


            <!-- Tika -->
            <dependency>
                <groupId>org.apache.tika</groupId>
                <artifactId>tika-core</artifactId>
                <version>${tika.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.tika</groupId>
                <artifactId>tika-parsers-standard-package</artifactId>
                <version>${tika.version}</version>
            </dependency>

            <!-- Spring - bcrypt -->
            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-core</artifactId>
                <version>${spring.security.version}</version>
            </dependency>

            <!-- SSL -->
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcmail-jdk18on</artifactId>
                <version>1.80</version>
            </dependency>

            <!-- HTTP Client -->
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp.version}</version>
            </dependency>

            <!-- Caching -->
            <dependency>
                <groupId>com.github.ben-manes.caffeine</groupId>
                <artifactId>caffeine</artifactId>
                <version>3.2.3</version>
            </dependency>

            <!-- Jackson -->
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${jackson-databind.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-yaml</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jsr310</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.module</groupId>
                <artifactId>jackson-module-jsonSchema</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>de.undercouch</groupId>
                <artifactId>bson4jackson</artifactId>
                <version>2.15.0</version>
            </dependency>

            <!-- PicoCLI -->
            <dependency>
                <groupId>info.picocli</groupId>
                <artifactId>picocli</artifactId>
                <version>${pico-cli.version}</version>
            </dependency>
            <dependency>
                <groupId>info.picocli</groupId>
                <artifactId>picocli-codegen</artifactId>
                <version>${pico-cli.version}</version>
            </dependency>
            <dependency>
                <groupId>me.tongfei</groupId>
                <artifactId>progressbar</artifactId>
                <version>0.10.0</version>
            </dependency>

            <!-- MetaLoom OSS deps -->
            <dependency>
                <groupId>io.metaloom.utils</groupId>
                <artifactId>utils</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.utils</groupId>
                <artifactId>differential-filesystem-scanner</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.utils</groupId>
                <artifactId>hash-utils</artifactId>
                <version>0.5.0-SNAPSHOT</version>
            </dependency>

            <!-- Video4j -->
            <dependency>
                <groupId>io.metaloom.video</groupId>
                <artifactId>video4j</artifactId>
                <version>${video4j.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.video</groupId>
                <artifactId>video4j-facedetect-inspireface</artifactId>
                <version>${video4j.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.video</groupId>
                <artifactId>video4j-fingerprint</artifactId>
                <version>${video4j.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.video</groupId>
                <artifactId>video4j-facedetect-insightface-http</artifactId>
                <version>${video4j.version}</version>
            </dependency>
            <dependency>
                <groupId>io.metaloom.video</groupId>
                <artifactId>video4j-facedetect-dlib</artifactId>
                <version>${video4j.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>